### ISSUE TITLE
Character Counter: default input value not counted correctly

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1001]
**Describe the bug**
When a Character Counter is used with an initial "value", the characters don't get counted

**To Reproduce**
1. Render a character counter with a starting "value"
2. Notice that on initial render, it's not counting the characters

**Expected behavior**
Characters are counted both when the field is initially empty and when it has a default starting value

**Screenshots**
![image](https://user-images.githubusercontent.com/91160746/216092824-c77c8791-f03d-4b30-acee-f2d949bc612e.png)

**Additional context**

**Comment by hkrishna29** [comment]
the issue no longer exists .  http://somup.com/c0nrYQyfWP | http://somup.com/c0nrY6yhcQ
