### ISSUE TITLE
Toast Container: Toasts don't stack as expected if more than one line 

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1010]
**Describe the bug**
Toasts don't stack as expected if more than one line.

Toasts in v2 used to be the same height for 1 or 2 lines (56px), but something changed in v3. 

**To Reproduce**
1. Go to https://next--upbeat-sinoussi-f675aa.netlify.app/api/toast/#toasts_container_(handling_multiple_toasts)
2. Click on the toasts from left to right

**Expected behavior**
Toasts don't overlap because they are the same height for 1 or 2 lines. We should also clarify in the docs that if a user's message extends to 3 lines, they need to shorten the message.

**Screenshots**
https://recordit.co/KwL18FG4Y3

**Additional context**
This worked in v2, but broken in v3

**Comment by hkrishna29** [comment]
the issue no longer exists http://somup.com/c0ejFhyuKA
