### ISSUE TITLE
Dropdowns with Accordion

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1014]
Need to finalize visual design for what it should look like to have an accordion inside a dropdown. Then, we should add an example in the docs site.

Quick example: https://codesandbox.io/s/dropdown-with-accordion-8uheek?file=/example.tsx

**Comment by orion-cengage** [comment]
Figma: https://www.figma.com/file/VoWYiiOKKppcYm5QLgPyDC/Components---Inputs?type=design&node-id=606%3A16350&t=6yAmjnYZwlYgQwt3-1

###ACs

1.0 When a list item in the dropdown is a parent with children, it gets a chevron on the right side to indicate it can be expanded.
-- 1.1 There should be a prop to show that parent item expanded by default.
-- 1.2 Clicking anywhere on the item (not just the chevron) should expand or collapse the item.
-- 1.3 Child items should be indented 32px to reinforce the hierarchy
-- 1.4 You can only have one level of children. Children can not also be parents with their own children.
-- 1.5 If you include icons on the parent level, the children do not also have icons.
-- 1.6 If you include icons on the parent level, children are indented 72px
2.0 You can insert dividers between items to create groups, same as with non-expandable items

**Comment by silvalaura** [comment]
@ccedrone Please provide testing notes & list of all use cases

**Comment by silvalaura** [comment]
Testing Notes: https://laura-silva.notion.site/Expandable-Dropdown-dd5c52a6072f4cfca8a6e64259f1a4a5?pvs=4 

There are a few questions and issues noted @ccedrone

**Comment by orion-cengage** [comment]
Feedback:

- Please adjust the focus outline on the top level items so it doesn't cut off on the sides. Looks like one way to do it is to change the offset to -2px. This will also help keep the focus outline from overlapping into adjacent menu items.

![Image](https://github.com/cengage/react-magma/assets/24397282/619f2563-c59f-481e-97f1-77891a94f8f7)

- There should only be 8px of padding at the top and bottom of the dropdown container. It looks like there is some extra padding being applied on a div inside that container, making the padding actually look more like 12px or 16px.

![Image](https://github.com/cengage/react-magma/assets/24397282/dce93e16-5556-4a7a-8417-482282763837)

- Did AC 1.1 get completed? There should be a prop to have one or more parent items automatically expanded.
