### ISSUE TITLE
docs(accordion): Upon selecting 'Accordion Panel Props', the scroll bar is moving down and automatically scrolls back up

### ISSUE THREAD

**Issue by hkrishna29** [cengage/react-magma#1034]
**Describe the bug**
Scrollbar moves down the page and automatically scrolls back up

**To Reproduce**
1. Go to https://docs-preview-972--upbeat-sinoussi-f675aa.netlify.app/api/accordion/
2. Click on 'AccordionPanel Props link'
3. Scrollbar scrolls down the page and automatically scrolls back up

**Expected behavior**
The scroll bar should not scroll back up unless the action is performed

**Screenshots**
https://somup.com/c0e3qMy7a3

**Desktop (please complete the following information):**
All OS/Combinations

**Note** 
When the option 'AppBar' is selected , the page is displayed but the scroll bar scrolls to the middle of the page automatically

**Comment by silvalaura** [comment]
Confirmed that this is behaving as expected now 🌟
