### ISSUE TITLE
Carbon Charts: Simple bar, Grouped bar, Floating bar, Lollipop

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1052]
_This is a placeholder ticket for specific requirements regarding our customization of Carbon Charts._

[Chart Types](https://carbondesignsystem.com/data-visualization/chart-types/)

Let's find a balance of customizing the styles to fit Magma so they look cohesive together, without changing so much that we lose the value of using this library to begin with.

Figma: https://www.figma.com/file/0tifcLtTm7TodIoR5gJsrX/Magma-Data-Visualization?type=design&node-id=101%3A3535&mode=design&t=hnGgDZwMGIOHDTED-1

Here's a list of customizations I'd like us to try to do:

1. I’d like to increase the font size and change color of the text in the little popovers.

![Image](https://github.com/cengage/react-magma/assets/24397282/072db275-627d-48ff-8c84-0dde54de9543)

2. I'd like to increase the size of the boxes/checkboxes in the legend to 16px.

![Image](https://github.com/cengage/react-magma/assets/24397282/ebe3a73f-2f11-459a-b935-6fb0f3d9b973)

3. On the modal that opens for the table view, round the corners of the modal to 8px.

![Image](https://github.com/cengage/react-magma/assets/24397282/95173b31-34d9-4f51-bc2c-7ab80b492386)

4. Let's try to make sure the focus outline matches our blue color everywhere it appears. This is an example of the wrong blue.

![Image](https://github.com/cengage/react-magma/assets/24397282/f176bbdb-c9a0-4567-85cd-331917edd9be)

5. Work with the styles of the button at the bottom of the modal

![Image](https://github.com/cengage/react-magma/assets/24397282/c59e8766-cd67-4c2b-a7d4-8b00fb8b1af4)

6. Work with the CSS so that the dark mode doesn't have a black background behind the chart

Updated color palette and order:

- #009AF3
- #E0004D
- #1EA746
- #FA6600
- #B12FAD
- #00A393
- #005F96
- #8F0033
- #136A2D
- #B84900
- #711E6E
- #005249

Dark mode

- #1FB0FF
- #FF337A
- #65E000
- #FF9147
- #D45ED0
- #00E0CA
- #85D4FF
- #FF99BD
- #FFB685
- #C7FF99
- #E9AFE7
- #99FFF5

**Comment by silvalaura** [comment]
We will mimic Carbon's storybook:
![image](https://github.com/cengage/react-magma/assets/91160746/d14d69bb-8ed2-4fe3-96b3-763e402dbc87)
![image](https://github.com/cengage/react-magma/assets/91160746/d856a18e-d3fc-4fdf-b500-c12c07117459)
![image](https://github.com/cengage/react-magma/assets/91160746/fcdcd2ab-6bdf-47d1-bdac-4d1bce4abb79)
![image](https://github.com/cengage/react-magma/assets/91160746/64d8b7e8-245d-4936-972d-154db75a1091)

**Comment by orion-cengage** [comment]
Feedback:

- Title text needs to be updated to #454545

![Image](https://github.com/cengage/react-magma/assets/24397282/80ce1a37-0c92-4d90-a735-15a72d834c3e)

- The squares are supposed to be 16px square.

![Image](https://github.com/cengage/react-magma/assets/24397282/fb8993e0-9a48-4e63-938c-98d884acd802)

- The text inside the popovers is supposed to be #454545. This looks darker.

![Image](https://github.com/cengage/react-magma/assets/24397282/9611beff-83a3-4577-97a2-15db87858cb3)

- All of the text in this modal is supposed to be #454545

![Image](https://github.com/cengage/react-magma/assets/24397282/a8cb5dd5-4856-40a3-9bf9-14c26df168e6)

- Make all text in the dark mode = white

![Image](https://github.com/cengage/react-magma/assets/24397282/9bcc2e99-0bc8-4717-8741-99d64bc2a927)

- Need to update colors of the tabular representation modal. I'll add that to a separate comment.

- In dark mode, the lines on the graph background are almost impossible to see. Let's try making the x and y axis white, and then the grid lines white at 50% opacity.

- Can we try removing the black border on those squares in dark mode?

![Image](https://github.com/cengage/react-magma/assets/24397282/dad5c6b1-7a7d-4436-a069-57b6d157ba0c)

- Can we try updating the focus color to use our inverse focus color?

![Image](https://github.com/cengage/react-magma/assets/24397282/aa938deb-b47e-4efd-8d07-93161534dfb9)

![Image](https://github.com/cengage/react-magma/assets/24397282/78a89d42-718c-4db5-8390-6312b733339b)

- On the dark mode loading skeleton, we need the background to not be black.

![Image](https://github.com/cengage/react-magma/assets/24397282/76c6949c-ff9d-46e3-8b1a-273c3784d333)

**Comment by orion-cengage** [comment]
Here is a guide to styling the modal

![Image](https://github.com/cengage/react-magma/assets/24397282/96c9db7b-484a-4ab6-9112-a2b64d706e9f)

**Comment by silvalaura** [comment]
As far as adding charts to docs, let's make sure:
- we are very clear we are re-skinning Carbon Charts (link to https://carbondesignsystem.com/data-visualization/chart-types/)
- recommendations for what type of chart for what kind of data (carbon does this)
- should we link to storybook or codesandbox? how many examples of each type do we need?
