### ISSUE TITLE
Dropdown - Dropdowns with form does not change focus

### ISSUE THREAD

**Issue by jerrodheiser** [cengage/react-magma#1063]
**Describe the bug**
Dropdown with form does not change focus, and results in irregular closing behavior.

**To Reproduce**
1. Go to https://codesandbox.io/s/4m9qn0?module=/example.tsx
2. Click on first Dropdown button.
3. Click on second Dropdown button.
4. Observe that focus is still on the first Dropdown button.
5. Click away from second Dropdown content
6. Observe that the second Dropdown does not close.

**Expected behavior**
Second dropdown closes

**Screenshots**

**Desktop (please complete the following information):**
 - Version 3.3.0

**Additional context**
-Works correctly in v4.0.0
-This bug is reproducable no matter what the type of the first Dropdown clicked is. As long as the second Dropdown clicked is a Dropdown form, then this behavior will be observed.

**Comment by silvalaura** [comment]
Can be tested here: https://storybook-preview-dev-patch--upbeat-sinoussi-f675aa.netlify.app/?path=/story/dropdown--no-items

**Comment by jerrodheiser** [comment]
Issue is no longer present on latest version of v3. Fix was implemented in v4, and subsequently brought into v3.
