### ISSUE TITLE
react-magma-docs: Add version dropdown to the docs

### ISSUE THREAD

**Issue by joasmi723** [cengage/react-magma#107]
We need to indicate to users which version of the docs they are on, and allow for them to change versions easily.   To do this, we should add a dropdown to the docs masthead, as shown in the image.  Selecting a different version from the dropdown should take them to the respective version of the docs.  Selecting `View all versions` should take them to `https://react-magma.cengage.com/`.  

![version dropdown](https://user-images.githubusercontent.com/18616182/105507307-a77d8800-5c90-11eb-921b-cc68072f56c3.png)

**Comment by joasmi723** [comment]
Versions can be gotten from here:  https://react-magma.cengage.com/versions

**Comment by silvalaura** [comment]
Lets also look into removing pre-releases from the changelog list: 
![image](https://user-images.githubusercontent.com/91160746/162445613-56bc46c9-183f-403f-9f17-7339d3c1688c.png)

**Comment by silvalaura** [comment]
This is obsolete. Replaced with https://github.com/cengage/react-magma/issues/316
