### ISSUE TITLE
List component should support nested list items

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1073]
**Describe the bug**
Our List component should support nested list items:

```
<List isOrdered={true}>
        <ListItem>List content</ListItem>
        <ListItem>List content</ListItem>
        <List>
          <ListItem>1 Nested List content</ListItem>
        </List>
        <List>
          <ListItem>2 Nested List content</ListItem>
        </List>
        <ListItem>List content</ListItem>
      </List>
```

**To Reproduce**
1. Go to https://codesandbox.io/s/rm-list-8u97jo?file=/example.tsx
2. Notice that nested lists are not supported

**Expected behavior**
Nested lists should work similarly to native lists

**Screenshots**
![image](https://github.com/cengage/react-magma/assets/91160746/627aa03a-dc54-495b-85bf-5a81529356e1)

**Notes**
Let's add an example of nested lists to the docs site

**Comment by silvalaura** [comment]
Relates to #413

**Comment by orion-cengage** [comment]
I verified the updated component works and looks as expected and I like the accompanying updates to the docs.
