### ISSUE TITLE
Date picker - Keyboard nav issues when NVDA is turned on

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1080]
**Describe the bug**
Reported by David Charters

When trying to navigate the date picker with NVDA turned on he is getting the following problems:

1. Can't navigate to the keyboard help button
2. page up/down home/end are not working

Here's a screenshot of his NVDA settings

![image](https://github.com/cengage/react-magma/assets/24397282/882fa8df-df55-4d36-a3f1-bbdf1756bb7a)

**Comment by silvalaura** [comment]
This is reproducible: 

https://github.com/cengage/react-magma/assets/91160746/5cfb773d-07c8-4e5c-98fb-e3eaea25be06

**Comment by silvalaura** [comment]
@chris-cedrone-cengage This ended up being a whole DatePicker navigation and accessibility overhaul, not exclusive to PC. I have confirmed it works on NVDA, so please confirm the use cases noted in the PR on Mac/VoiceOver.

**Comment by chris-cedrone-cengage** [comment]
Open DatePicker -> Open HelperInformation -> Press Tab several times -> Focus inside HelperInformation. ✅

Open DatePicker -> Open HelperInformation -> Return back to DatePicker -> Press Tab several times -> Focus inside DatePicker. ✅

Button X (Close HelperInformation) in HelperInformation has the same behavior as the Return back to Calendar button. ✅

Open DatePicker -> Open HelperInformation -> Press X -> Closed DatePicker. ✅

Open DatePicker -> Press Tab several times -> Focus on dates. ✅

Open DatePicker with inactive days (minDate) -> Select the day right after inactive -> Press ArrowUp or ArrowLeft several times -> No need to press several times ArrowDown or ArrowRight to come back to the focused day. The focus shows the exact position selected. ✅

I think we should add showing the focus on the Keyboard Icon so when a user opens the help panel, then clicks back to calendar, the focus is visible. ✅

**All verified with VoiceOver using Mac OS Sonoma 14.7**

**Comment by chris-cedrone-cengage** [comment]
Safari 18 Shows the following behavior:

Date picker -> Tabbing closes Date picker window at the end of focusable elements instead of looping back through them

Date picker -> Keyboard instructions -> Tabbing loses focus behind date picker

**Comment by silvalaura** [comment]
I can't reproduce the issue above, but 4 people can, so this needs to be reviewed and addressed.

**Comment by silvalaura** [comment]
@chris-cedrone-cengage 
Verify that with this command, you can see it working:
Control-F7 or Fn-Control-F7: Change the way Tab moves focus—between navigation of all controls on the screen, or only text boxes and lists.

**Comment by chris-cedrone-cengage** [comment]
Works with _**Fn-Control-F7**_ toggled in Safari 18
