### ISSUE TITLE
Bug: Combobox - label breaks from container on certain length

### ISSUE THREAD

**Issue by ccedrone** [cengage/react-magma#1081]
**Describe the bug**
Reported by Alexandra Malyshenko. 

**Expected behavior**
Label should not break outside of containing element in the Combobox.

**Screenshots**
![Combobox error](https://github.com/cengage/react-magma/assets/77400920/f765d1a2-c33c-472b-aa65-abda0d1f1766)

**Comment by silvalaura** [comment]
No plans to fix.
