### ISSUE TITLE
Pagination: Focus on previous page arrow is hidden

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1083]
**Describe the bug**
When the focus is set on the 'previous page' arrow it is partially hidden beyond the '1' button.

**To Reproduce**
1. Go to https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/pagination--default
2. Click on 2
3. Shift+tab+left two times and notice the focus

**Expected behavior**
The focus state is fully visible

**Screenshots**
![image](https://github.com/cengage/react-magma/assets/91160746/8d30fc85-b266-4e54-9497-e2c1615da5d0)

**Comment by silvalaura** [comment]
Dupe of #1084

**Comment by orion-cengage** [comment]
Verified fix. Looks good.
