### ISSUE TITLE
PasswordInput: Show button in size large is off center

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1088]
**Describe the bug**
The show button in the large PasswordInput is in the wrong place

**To Reproduce**
1. Go to https://next--upbeat-sinoussi-f675aa.netlify.app/api/password-input/

**Screenshots**
![image](https://github.com/cengage/react-magma/assets/91160746/6fe57418-0840-463a-9bc5-b2575bcffa38)

**Notes**
In addition to fixing the above for large inputs, lets also polish up the show/hide button in the regular size

**Comment by ccedrone** [comment]
Looks good here!
