### ISSUE TITLE
NavTab: Support overwriting TextTransform

### ISSUE THREAD

**Issue by noahwebs** [cengage/react-magma#1107]
**Is your feature request related to a problem? Please describe.**
When using Tabs and NavTabs, the `text-transform` is hardcoded to uppercase which goes against the style my UX team has prescribed for my use case. 

**Describe the solution you'd like**
In the same way that the Button component allows setting the textTransform through the ButtonTextTransform property, Tabs and NavTabs should support a TabTextTransform property. 

**Describe alternatives you've considered**
As a workaround, I can insert a styled span to overwrite the `text-transform` property, but this workaround is annoying to reimplement every time.

**Acceptance Criteria**
- NavTabs and Tabs have a `textTransform` prop that defaults to `TabsTextTransform.uppercase`

**Comment by chris-cedrone-cengage** [comment]
Open Tabs/NavTabs in docs/storybook -> Set TextTransform property -> Check styles. ✅

Verified in:
https://storybook-preview-1494--upbeat-sinoussi-f675aa.netlify.app/
