### ISSUE TITLE
Support "Additional Children (e.g. Help Link)" for Select components

### ISSUE THREAD

**Issue by noahwebs** [cengage/react-magma#1114]
**Is your feature request related to a problem? Please describe.**
Input components support additional children such as help links in the case that the field in question needs further explanation that isn't appropriate to the Helper Message. It would be helpful if Select components also supported this feature so that Input and Select elements on a form could maintain feature parity.

**Describe the solution you'd like**
The Select component would implement "child elements" in the same way that Input components do.

**Describe alternatives you've considered**
- Rolling my own Select component to match the Input component style. This could cause feature drift and defeats the purpose of using a component library.
- Abusing the "labelStyle" property to somehow have the label be super wide with left floated text and right floated help icon. This feels hacky and I don't even know if it could work. 

**Additional context**
N/A unless more is asked of me.

**Comment by jwad03** [comment]
Include native select as well as custom

**Comment by silvalaura** [comment]
Testing Notes:

https://codesandbox.io/p/sandbox/select-additionalcontent-test-xtkmfk?file=%2Fexample.tsx%3A2%2C9

- CodeSandbox is broken: import paths are broken for both Select and NativeSelect ❌
- CodeSandbox shows error with NativeSelect (missing fieldId)❌
- Works with and without Tooltip ✅
- Behaves as expected with top label position ✅
- Behaves as expected with left label position ✅ 
- Behaves as expected with hidden label ✅ 
- Looks fine when other components are thrown inside `additionalContent`✅

**Comment by silvalaura** [comment]
Testing Notes:
- Confirmed CodeSandbox works without broken paths or errors for both Select and NativeSelect
