### ISSUE TITLE
DropdownContent doesn't handle "false" as child

### ISSUE THREAD

**Issue by noahwebs** [cengage/react-magma#1131]
**Describe the bug**
DropdownContent crashes if one of its children is "false". A common pattern within React components is to conditional render a component using the `{boolean && <Component/>}` pattern. For example within the DropdownContent component, you may want to include/exclude a DropdownMenuItem based on a React component state or function's return value.

```
<DropdownContent>
   {canStart() && <DropdownMenuItem>Start<DropdownMenuItem>}
   {canStop() && <DropdownMenuItem>Stop<DropdownMenuItem>}
   <DropdownMenuItem>View<DropdownMenuItem>
</DropdownContent>
```

If one of the children evaluates to false, then the DropdownContent component crashes with this error:
<img width="899" alt="Screenshot 2023-09-14 at 10 26 54 AM" src="https://github.com/cengage/react-magma/assets/88386737/c2a47a46-48b7-4371-aa6d-dc2749a2278a">

**To Reproduce**
1. Create a DropdownComponent like this:
```
<Dropdown>
  <DropdownButton>Basic Dropdown</DropdownButton>
    <DropdownContent>
    {false && <DropdownMenuItem>Menu item 1</DropdownMenuItem>}
    <DropdownMenuItem>Menu item number two</DropdownMenuItem>
    <DropdownMenuItem disabled>Disabled item</DropdownMenuItem>
  </DropdownContent>
</Dropdown>
```
2. Render it and see the error

**Expected behavior**
The above Dropdown should render with the "Menu item number two" and "Disabled menu item" options available.
![Screenshot 2023-09-14 at 10 31 21 AM](https://github.com/cengage/react-magma/assets/88386737/c7a26915-2de1-4988-a180-e9821f844331)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
This should be a pretty easy fix actually. In DropdownContent.tsx, just add null handling on the child variables
![Screenshot 2023-09-14 at 10 33 23 AM](https://github.com/cengage/react-magma/assets/88386737/9ed5c9c2-bba0-4419-80fe-b39f7baca6e8)

Should be 
![Screenshot 2023-09-14 at 10 34 48 AM](https://github.com/cengage/react-magma/assets/88386737/e0b2c556-8b01-445f-9142-b4669d325286)

**Workaround** 
Working around this is also pretty easy. If you pre-evaluate the Menu items instead of passing them inline, then it doesn't crash.

```
const menuItems = <>
   {canStart() && <DropdownMenuItem>Start<DropdownMenuItem>}
   {canStop() && <DropdownMenuItem>Stop<DropdownMenuItem>}
   <DropdownMenuItem>View<DropdownMenuItem>
</>;

<DropdownContent>
{menuItems}
</DropdownContent>
```

**Comment by silvalaura** [comment]
Good find! Are you able to open a PR with this fix?

**Comment by noahwebs** [comment]
Committing code to the Magma repo is still uncommon enough for me that the overhead of context switching and creating a PR is non-trivial. I had hoped that since this was really easy to fix, the Magma core team could get to this if/when they had a chance to knock out something so simple. 

I actually have a way to work around this (and I'll add it to the description now), so it's not pressing for me to address.

**Comment by ccedrone** [comment]
Verified the fix as working, no more errors appear on screen. Via: https://next--upbeat-sinoussi-f675aa.netlify.app/api/dropdown/
