### ISSUE TITLE
Safari > Dropdowns won't close on second button click

### ISSUE THREAD

**Issue by chris-cedrone-cengage** [cengage/react-magma#1142]
**Describe the bug**
Safari doesn't close a Dropdown when using the Dropdown button. It remains on the screen after a second button click.

**To Reproduce**
1. In Safari, go to the doc site.
2. Go to Dropdown.
3. Click on any Dropdown button to open a Dropdown, then click again to close.
4. Notice that the Dropdown remains open on the second click.

**Expected behavior**
When a Dropdown button click opens a Dropdown, that same button should close the Dropdown when clicked again.

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura
 - Safari
 - Version 16

**Notes**
- Is there anything we can do about this? Any work arounds? Or do we just have to live with this?

**Comment by silvalaura** [comment]
This comment describes the problem: https://github.com/downshift-js/downshift/issues/443#issuecomment-395227968

> The problem seems to be that Safari on iOS triggers a blur event before the onClick event

**Comment by chris-cedrone-cengage** [comment]
Tested with **Safari 18** in **Sonoma 14.7**:

https://docs-preview-1460--upbeat-sinoussi-f675aa.netlify.app/ ✅
https://storybook-preview-1460--upbeat-sinoussi-f675aa.netlify.app/ ✅
