### ISSUE TITLE
New Component: Navigation > Stepper

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1143]
**Purpose:** Create new Stepper component for multi-step processes

**Figma:** https://www.figma.com/file/cPCfDVWC38T7Qt3dIL95sR/Components---Navigation?type=design&node-id=701%3A1229&mode=design&t=CiJHJjCC5jvgsmwM-1

![image](https://github.com/cengage/react-magma/assets/24397282/399225d5-9060-4656-bf16-da0bf5e2ed60)

### 1.0  Stepper can support any number of steps
-- 1.1  Should we enforce a minimum of two or rely on people not to be ridiculous?
-- 1.2 Stepper orientation can be horizontal or vertical (to be added in #1208 )(two separate components?)

### 2.0  Step anatomy
-- 2.1  Labels on every step
--- 2.1.1  Primary label
--- 2.1.2  Secondary label

![image](https://github.com/cengage/react-magma/assets/24397282/3f04ab80-749c-421a-ab8a-cee506e2e274)

-- 2.2 Option to hide labels

![image](https://github.com/cengage/react-magma/assets/24397282/675a7e0b-af14-47e9-8904-0c00fa41f228)

-- 2.3 Option to show step summary instead of labels on each step
--- 2.3.1 Step Summary shows the primary and secondary labels for the current step.
--- 2.3.2 The string that reads "step # of #" needs to be customizable so it could say things like "question # of #" or "module # of #".
--- 2.3.3 This could perhaps be done by Summary being a separate component and showing how to use it with the Stepper.

![image](https://github.com/cengage/react-magma/assets/24397282/a7c48aa3-b904-447b-bb09-9dcdac9aaff4)

-- 2.4  Status indicator
--- 2.4.1  Statuses include: 
---- 2.4.1.1 Current step

![image](https://github.com/cengage/react-magma/assets/24397282/0a17f650-6d35-46de-8866-3565cc6cdf2b)

---- 2.4.1.2 Completed Step

![image](https://github.com/cengage/react-magma/assets/24397282/88a4b47b-1c91-4a7c-b8d2-c83cf139858a)

---- 2.4.1.3 Incomplete Step

![image](https://github.com/cengage/react-magma/assets/24397282/4b8f3ebc-0f91-4b1d-a5d2-392e593405c1)

---- 2.4.1.4 Error

![image](https://github.com/cengage/react-magma/assets/24397282/409f0c91-69f0-4bb9-a94a-9e46e8c24acb)

-- 2.5  There is a connecting line between each step
---  2.5.1  The color of the line changes depending on the status of the steps it is connecting
---- 2.5.1.1  Completed to Completed = Bold
---- 2.5.1.2  Completed to Current = Bold
---- 2.5.1.3  Current to Future = Subtle
---- 2.5.1.4  Future to Future = Subtle

![image](https://github.com/cengage/react-magma/assets/24397282/108f5b6a-b775-4ddb-a01b-8b1dff3e9ea8)

![image](https://github.com/cengage/react-magma/assets/24397282/d025ceb2-bc27-4dba-b4cb-80b4d4b06120)

### 3.0 Interaction
-- 3.1  First and foremost, the Stepper is an indicator of what step the user is on. In this potential first phase, we are not going to make it interactive to the point where you can click to other steps. Controls for navigating the various steps will need to be built into the main content area.

### 4.0 Responsive behavior

It's questionable how much of this we should bake into the component vs. just make it possible and document examples. But essentially, here are the kinds of changes someone would want to make as the screen gets smaller.

-- 4.1 Consumer chooses what breakpoint there should be, if any at all.
-- 4.2 Horizontal Stepper
--- 4.2.1 Consumer might want to change to no labels

![image](https://github.com/cengage/react-magma/assets/24397282/7f9f9962-7616-4130-b177-3fb1517d538f)

--- 4.2.2 Consumer might want to change to Summary

![image](https://github.com/cengage/react-magma/assets/24397282/f5d96e2b-9821-4727-84a8-aab718e35e35)

### 5.0 Content area
-- 5.1 We don't need to build a content area into the component, but we should include simple examples of how to do this in the demos in the documentation.
--- 5.1.1 In the demos we should include:
---- 5.1.1.1 Section Title that changes as the step changes
---- 5.1.1.2 "Back" and "Next Step" buttons that interact with the Stepper accordingly

![image](https://github.com/cengage/react-magma/assets/24397282/d7b95c4d-0a80-4b6f-bd2f-ea60a3ff96fd)

### 6.0 Accessibility
-- 6.1 The accessibility guidelines found here might provide some nice inspiration for our component in terms of aria attributes, etc.
--- https://designsystem.digital.gov/components/step-indicator/#accessibility
-- 6.2 If we make the steps clickable someday, we may have to wrap the component in a "nav" element, but I don't think it is necessary for this implementation.

### 7.0 Dark Mode
-- 7.1 See Figma for Dark Mode design

![image](https://github.com/cengage/react-magma/assets/24397282/8c3b9e62-43b7-463e-b160-99321e9bdfc9)

**Comment by silvalaura** [comment]
I put together this draft Stepper a while back for magma v2.5. Dropping it here in case it's helpful when building this: https://codesandbox.io/p/sandbox/react-magma-stepper-6u61l8?file=%2Fstep.tsx
