### ISSUE TITLE
Update Expressive Text Styles

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1156]
A request has been made by Marketing to adjust the Expressive text styles in our next release.

### New Desktop styles (font-size/line-height):
- Heading 2XL = 64px/84px, 500 weight
- Heading XL = 48px/64px, 600 weight
- Heading L = 36px/48px, 600 weight
- Heading M = 28px/40px, 600 weight
- Heading S = 24px/32px, 500 weight
- Heading XS = 20px/32px, 500 weight
- Heading 2XS = 18px/24px, 500 weight
- Body Large = 20px/32px, neutral-700 color

### New Mobile styles (font-size/line-height):
- Heading 2XL = 48px/64px, 500 weight
- Heading XL = 36px/48px, 600 weight
- Heading L = 28px/40px, 600 weight
- Heading M = 24px/32px, 500 weight
- Heading S = 20px/32px, 500 weight
- Heading XS = 18px/24px, 500 weight
- Heading 2XS = 16px/24px, 500 weight

### Desktop
![image](https://github.com/cengage/react-magma/assets/24397282/6ebd8159-ea4d-4ffc-84c3-a0229c1b1c4d)

### Mobile
<img width="961" alt="image" src="https://github.com/cengage/react-magma/assets/24397282/54da0fdc-e4da-466e-82d6-a8051ddf292b">

**Comment by silvalaura** [comment]
Release December or early January

**Comment by silvalaura** [comment]
This CodeSandbox can be used to test all the updated Expressive styles: https://codesandbox.io/p/sandbox/expressivestyles-6yqwyv?file=%2Fexample.tsx%3A7%2C26

**Comment by orion-cengage** [comment]
I haven't been able to get the codesandbox link to load, but I QA'd the DEV docs and they look good.
