### ISSUE TITLE
Search: `isClearable`X overlaps with content

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1161]
**Describe the bug**
The Search component with `isClearable` is missing the additional padding we have in Input to prevent the X from overlapping the content.

**Expected behavior**
The X does not overlap the text inside the input

**Screenshots**
![image](https://github.com/cengage/react-magma/assets/91160746/cbf8476e-a44b-40e7-bdc9-0a5ed15f9984)

**Comment by chris-cedrone-cengage** [comment]
The X does not overlap the text inside the input ✅

Verified in:

https://docs-preview-1474--upbeat-sinoussi-f675aa.netlify.app/api/input/ ✅
https://storybook-preview-1474--upbeat-sinoussi-f675aa.netlify.app/?path=/story/input--default ✅
