### ISSUE TITLE
Dropdown: DropdownButton prop of onClick doesn't do anything when called.

### ISSUE THREAD

**Issue by ccedrone** [cengage/react-magma#1174]
**Describe the bug**
When trying to call a function with `onClick`, nothing gets returned.

**To Reproduce**
1. Go to Dropdown in docs
2. In first example, click on edit in codesandbox
3. Add 'onClick' to DropdownButton to verify nothing returns

**Expected behavior**
This prop should allow for a custom event.

**Comment by silvalaura** [comment]
Functioning as designed-- onClick is handled by onOpen and onClose on `Dropdown`
