### ISSUE TITLE
Investigate CodeSandbox's pricing model change

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1190]
https://www.codesandbox.community/c/api-billing-updates/upcoming-pricing-billing-changes

- How does this affect our docs site?
- How does it affect our ability to provide examples for people seeking help in our support channel?
- Can we keep the free tier or do we need to upgrade? is there budget for this?

**Comment by silvalaura** [comment]
- This does not affect our docs site 🎉 Everyone, even if they are out of sandboxes, can view our examples. However, they will need to sign in to make edits and edit the code. This requires available sandboxes for their account.
- We are still able to provide examples for people that ask for our help through sharable links. However, we are limited to 10 drafts and 20 sandboxes. This is inconvenient and does not allow us to keep old sandboxes that we can go back to for reference. The main use case for this was when we were keeping sandboxes for reference on how we QA'd a ticket and the use cases we were going through. I am always at the limit and have to find something to delete in order to create a new sandbox to share with someone or try putting something together.
- It would cost $12 per month per workspace (or $9 per month if billed annually) to have unlimited sandboxes and drafts. We may be able to get a discount for being an open source project. I believe we would be able to have 1 workspace for our entire team (up to 20 members). [Pricing model link](https://codesandbox.io/upgrade?workspace=341d9c02-db5c-4a9c-adec-82f37a2caac1)

**Comment by MelvinSE** [comment]
Thanks Laura.  We will take this to review.
