### ISSUE TITLE
Modal: Background overlay issue on nested modals

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1200]
Issue: The following issue occurs when using the nested modal functionality. When you open the second modal, an additional background overlay is rendered appropriately, but it is placed under the first modal, which is incorrect. It should be placed between the first and second modal in order to "fade out" the first modal and bring the second modal to the front.

https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/modal--modal-in-a-modal

https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/modal--close-modal-with-confirmation

![image](https://github.com/cengage/react-magma/assets/24397282/60c85251-1f4c-463a-bc21-02252c759383)

![image](https://github.com/cengage/react-magma/assets/24397282/c7eb7870-b2dc-43fd-b614-7efa9fe8284e)

Acceptance Criteria:
- Single modals remain unchanged
- Nested modals have the background right behind them

**Comment by silvalaura** [comment]
MAST is using a lot of modals over modals and would love to get this fixed.

**Comment by silvalaura** [comment]
Confirmed that when using 2 or 3 modals, the background overlay behaves as expected:


![Image](https://github.com/user-attachments/assets/5e6fc81a-0edb-4110-a9c1-084955c91c30)

![Image](https://github.com/user-attachments/assets/3ebc4ed0-af3f-4782-8ccc-178d8bb5d617)

**Comment by silvalaura** [comment]
This caused an issue with drawers in small screens:

![Image](https://github.com/user-attachments/assets/ac88f989-23bf-4a0a-8a5c-ef0a8c257909)
