### ISSUE TITLE
Select: Support disabling individual items

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1217]
Currently you can only disable the entire Select component, but not individual items within it. We should support this. 

```
items={[
          {
            { label: 'Red', value: 'red', disabled: false },
            { label: 'Blue', value: 'blue', disabled: true },
          },
}]
```

![image](https://github.com/cengage/react-magma/assets/91160746/ec89c576-d32b-4834-b6c5-5e539b4ae85d)

**Comment by moathabuhamad-cengage** [comment]
@orion-cengage whats the styling  and expected behavior when it comes to keyboard navigation and screen readers for the disabled items

**Comment by silvalaura** [comment]
@moathabuhamad-cengage The behavior should be similar to that of a Native Select (https://codesandbox.io/p/sandbox/native-select-disabled-item-7h9p2q?file=%2Fexample.tsx). 

As far as styling, I think we use `transparentize(0.4, magma.colors.neutral500)` everywhere we disable items.

**Comment by chris-cedrone-cengage** [comment]
**Tested on:**
https://next--upbeat-sinoussi-f675aa.netlify.app/api/select/
&
https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/select--with-disabled-items

@moathabuhamad-cengage Both function perfectly, however do we want to add `cursor: not-allowed` to disabled items when hovered upon?

**Comment by moathabuhamad-cengage** [comment]
keeping it default as per this discussion  https://github.com/cengage/react-magma/pull/1493#discussion_r1829600659
