### ISSUE TITLE
SPIKE: Figure out next steps on doc site build

### ISSUE THREAD

**Issue by jwad03** [cengage/react-magma#1224]
We need to figure out what to do about our docs site. We are currently using Gatsby v3, which is no longer supported and 2 versions behind.

**Some considerations:**
- How do we keep our dependencies up to date and avoid staying so far behind?
- ~~How do we make our docs site compatible with our upcoming Carbon Charts work?~~
- What is the level of effort for each of the options below, and which makes the most sense considering our future work?

**Options:**
- Upgrade to v4
- Upgrade to v5
- Move away from Gatsby and replace with NextJS

--- 
(from conversation with Ryan)
**What are the pain points / why should we consider moving away from Gatsby?** 
> Pain points: 
> - Does not play well with storybook 
> - Has underlying dependencies that have not been updated in a while 
> - GraphQL is sitting on Gatsby, so this may be the biggest challenge about moving away from it 
> 
> Suggestions:  
> - NextJS would be a great alternative to consider 
> - Timebox investigating the upgrade

**Comment by moathabuhamad-cengage** [comment]
Based on my investigation, I propose that we upgrade to Gatsby v5 as the next step. This allows us to address current compatibility and dependency concerns without taking on a large migration effort in the short term.

Once Gatsby v5 reaches its end of life, we can then transition to Next.js to future-proof our documentation platform and benefit from its flexibility and compatibility with our tech stack. 

its worth noting the current trajectory of Gatsby according to https://stateofjs.com/en-US/

![image](https://github.com/user-attachments/assets/67337889-27d3-4415-8cd0-8a209eb83d6a)

![image](https://github.com/user-attachments/assets/743c0332-8f10-4b2d-9f9a-6ac930b21b83)

**Comment by silvalaura** [comment]
Sounds like a good plan!

**Comment by silvalaura** [comment]
@moathabuhamad-cengage Just wondering, do we need to move to React 18 to move to NextJS?

**Comment by moathabuhamad-cengage** [comment]
yes we generally do to avoid running in problems, from NextJs docs: 
> Next.js suggests using, at a minimum, react@18.2.0 and react-dom@18.2.0. Older versions of react and react-dom do work with Next.js, however, they do not enable all of Next.js' features.
