### ISSUE TITLE
Combobox - Focus is moved incorrectly after triggering Clear button

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1234]
CENG_3316

Docs: https://react-magma.cengage.com/version/4.3.0/design/combobox/

Success Criteria: https://www.w3.org/WAI/WCAG21/Understanding/focus-order

In the Clearable example, when the clear button is pressed it seems like focus is brought to the outer container of the combobox rather than the input itself. Because of this, a screen reader will announce that the user is in a combobox but the keyboard commands associated with a combobox will not work as expected.

When the combobox is cleared, send focus to the input within the combobox.

Steps to reproduce problem:

1. `Tab` to the input, notice focus is visually on the input container
2. Press `Space bar` and the panel of choices opens
3. Press `Enter` to select an option
4. `Tab` to the `Clear button`
5. Press `Enter` to clear the input
6. The `Clear button` disappears and the focus visually goes back to the input container and pressing `Space bar` again should open the panel of options BUT... it actually scrolls the page. 

This means the focus is probably actually on something else behind the code or maybe the keyboard controls get screwed up.

**Comment by silvalaura** [comment]
Relates to [#1390](https://github.com/cengage/react-magma/issues/1390)

**Comment by orion-cengage** [comment]
I have reviewed this by testing the component in Storybook. I turned on `isClearable`, and then using my keyboard I selected values, cleared them, and after the clearing I was immediately able to use my keyboard as expected to reveal the menu of options. This appears fixed and good to go.
