### ISSUE TITLE
Nav Tabs - indicating current page

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1238]
CENG_3321

Docs: https://react-magma.cengage.com/version/4.3.0/api/nav-tabs/

Success Criteria: https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships

In all of the Nav tab examples, the current page can be determined visually but not programatically. When going through navigations like this, it can be helpful to know if a link is where you currently are.

Use aria-current="page" on the currently active link to indicate the selected state of the component to screen reader users.

**Comment by silvalaura** [comment]
@orion-cengage do we think this is needed for Tabs as well?

**Comment by chris-cedrone-cengage** [comment]
All set!
