### ISSUE TITLE
Drawer - Wrong focus after closing

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1240]
CENG_3325

Docs: https://react-magma.cengage.com/version/4.3.0/api/drawer/

Success Criteria: https://www.w3.org/WAI/WCAG21/Understanding/focus-order

When any of the drawers are dismissed by pressing the Esc key or by activating the X (close) button in the dialog, the focus returns to the top of the page, rather than to the control that launched the modal.

When users dismiss the drawer/modal, always return the focus to the original control.  Otherwise, both screen-reader and keyboard users will have to navigate back to the control to find their previous place on the page.

**Comment by silvalaura** [comment]
Maybe related to https://github.com/cengage/react-magma/issues/970?

**Comment by silvalaura** [comment]
I think this may just be a problem with our examples. We don't have the equivalent of what we do in the Modal examples:
```
function handleOnClose() {
    setShowModal(false);
    buttonRef.current.focus();
  }
```

**Comment by chris-cedrone-cengage** [comment]
fix(drawer): Corrected examples for a drawer component to ensure focus returns to the opening button after the drawer **closes.** ✅

Verified in:
https://docs-preview-1475--upbeat-sinoussi-f675aa.netlify.app/ ✅
https://storybook-preview-1475--upbeat-sinoussi-f675aa.netlify.app/ ✅
