### ISSUE TITLE
Drawer - Focus not trapped properly when open

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1241]
CENG_3326

Docs: https://react-magma.cengage.com/version/4.3.0/api/drawer/

Success Criteria: https://www.w3.org/WAI/WCAG21/Understanding/focus-order

In all drawers, the keyboard focus is trapped within the modal in both directions *except* for the navigation drawer,  Here, the focus is trapped when tabbing forward, but when tabbing backward (Shift+Tab) the focus moves into the page behind the drawer.

(Note that the inverse view of the navigation drawer *does* trap the focus in both directions.)

Ensure that the keyboard focus remains trapped within the navigation drawer when users press Shift+Tab to move the focus backward.

**Comment by silvalaura** [comment]
Wonder if this is related to https://github.com/cengage/react-magma/issues/970 in some way?

**Comment by silvalaura** [comment]
Confirmed that all examples in docs site and storybook trap the focus as expected ✅
