### ISSUE TITLE
Animated progress bar - Need to honor reduced motion media query

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1242]
CENG_3328

Docs: https://react-magma.cengage.com/version/4.6.0/api/progress-bar/#animated

Success Criteria: https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide

For the animated progress bar, an animation like this could be distracting for users with some types of disabilities and dangerous for others. For this reason it is important to give users the ability to pause, stop, or hide non-essential animations like this.

### Solution

If the user has the `prefers-reduced-motion` media query set, then we need to turn off the animation on the progress bar, resulting in a normal static progress bar.

**Info about `prefers-reduced-motion` media query:** https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by silvalaura** [comment]
We already have logic to use the `reducedMotionTransition` theme: https://github.com/cengage/react-magma/blob/chore%2Fsync4.6.0/packages/react-magma-dom/src/components/Transition/Transition.tsx#L124. We may need to make adjustments to that file to ensure the progress bar doesn't change.

To test the reduced motion in macOS: System Preferences > Accessibility > Display > Reduce motion.
