### ISSUE TITLE
Update progress bar component to accept custom color indicator

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1333]
Purpose: Allow consumers to change the indicator of the progress bar to any custom color they want, in addition to our presets.

![image](https://github.com/cengage/react-magma/assets/24397282/1106c127-c28f-47ed-befc-73b4ea7251a3)

AC

- Allow consumer to use a string like "#B12FAD" to set the color of the indicator.
- Make sure the track can still not be changed.
- How can we handle allowing a different color set when Inversed?

**Comment by silvalaura** [comment]
Make a note in the docs site that, when using custom colors, they must be checked for color contrast for a11y.

**Comment by silvalaura** [comment]
Create an example that swaps between using chartColorsInverse and chartColors depending on whether the ProgressBar is using inverse.

**Comment by orion-cengage** [comment]
QA complete - Update to progress bar and documentation looks great.

**Comment by ccedrone** [comment]
Looks good here!
