### ISSUE TITLE
A11y: Date picker calendar table bug

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1340]
CENG_3414

[https://react-magma.cengage.com/version/4.4.0/api/date-pickers/](https://react-magma.cengage.com/version/4.4.0/api/date-pickers/)

### Description:
The table used for the calendar has `role=”presentation”` on the table element, despite it being a legitimate data table. This eliminates all of the (otherwise correctly applied) table semantics/labelling.

### Remediation:
Remove role="presentation" from the `<table>` element.

![image](https://github.com/cengage/react-magma/assets/24397282/0faf43f3-dc78-4e68-8f0d-fec5574afd93)

**Comment by silvalaura** [comment]
Confirmed `role=presentation` is no longer present in DatePicker

![Image](https://github.com/user-attachments/assets/88fdb815-d9f8-4294-97ff-2028c9fdc857)
