### ISSUE TITLE
A11y: Date picker calendar, days of the week aria-label

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1341]
CENG_3415

[https://react-magma.cengage.com/version/4.4.0/api/date-pickers/](https://react-magma.cengage.com/version/4.4.0/api/date-pickers/)

### Description:
The table headers are terse; just letters to represent days. Although descriptive labels are used for the buttons within cells, it is not necessarily by button focus that a screen reader would be traversing the table.

### Remediation:
Recommended each column header has an `aria-label` that replaces (for example) “T” with “Tuesday”. This will produce some redundancy, since the buttons describe the full day, but is a “belt and braces” approach.

![image](https://github.com/cengage/react-magma/assets/24397282/4c002ec7-93b8-4a1c-9567-1c97ca3ca5ba)

**Comment by chris-cedrone-cengage** [comment]
Verified on:

https://next--upbeat-sinoussi-f675aa.netlify.app/api/date-pickers/

&

https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datepicker--default

Add aria-label to calendar header columns. ✅
