### ISSUE TITLE
TreeView: Support `checkParents` prop

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1369]
**Is your feature request related to a problem? Please describe.**
The TreeView component should support the ability to select a nested item without selecting its parent.

**Describe the solution you'd like**
Add support for `checkParents` prop:

**checkParents**—Determines if the parent checkbox will get selected when the user selects all its children checkboxes. The default value is true. When checkParents is enabled, the TreeView displays the indeterminate state of the parent checkboxes too.

- This will only work for multi select trees
- Example: https://www.telerik.com/kendo-angular-ui/components/treeview/api/CheckableSettings/#toc-checkparents/

**Comment by orion-cengage** [comment]
The new update looks great from my perspective, but in the process of testing it looks like the section about Preselected Items isn't working. It looks like some items in the example should be preselected but they're not, and this could be a result of the update.

**Comment by silvalaura** [comment]
@k4rnaj1k We noticed that the addition of `checkParents` and `checkChildren` breaks when used in conjunction with `preselectedItems`.

In this example https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/treeview--complex&args=checkParents:false;checkChildren:false, there are 6 items that are passed to preselected but all the parents/children are also selected for a total of 9.

**Comment by k4rnaj1k** [comment]
As it turns out, some of it is caused by this bug in older versions of storybook:
https://github.com/storybookjs/storybook/issues/18796

And adding this to line 401: 
![image](https://github.com/user-attachments/assets/cef62580-508e-4260-8729-57de4e8b746e)
Makes the component behave more correctly.

However, there is a bug in how preselected items are checked that appeared before #1409 - pt1ch1.1 is also preselected, but not shown among selected items at the bottom, and selected items count is incorrect - says 9 instead of 10. 
![image](https://github.com/user-attachments/assets/f340b358-cba8-4676-8e67-7c2d906f815b)

**Comment by silvalaura** [comment]
Thanks @k4rnaj1k ! We'll look into this. 

Outstanding work:
1. Fix the line of code that k4rnaj1k mentions (adding  `&& checkParents`)
2. Then, we should confirm that the example https://next--upbeat-sinoussi-f675aa.netlify.app/api/tree-view/#preselected_items in the docs behaves as expected-- we expect to see birds and amphibians checked when the page loads
3. Dig in to the issue mentioned in the comments-- pt1ch1.1 should be selected even though it’s not in the list of preselected (because it’s the child of a preselected item), but it should also appear on the list of tags and count of tags

**Comment by silvalaura** [comment]
Items 1-3 have been addressed in https://github.com/cengage/react-magma/pull/1432. 
Moving item 4 above to a new ticket https://github.com/cengage/react-magma/issues/1433 as it's unrelated to `checkParents`.

**Comment by orion-cengage** [comment]
I was able to verify on the docs site that the new stuff is working and the pre-selected items example is working again as well. Moving to Done.
