### ISSUE TITLE
A11y Feedback: Pagination - fix aria-current attribute on current page

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1388]
CENG_1961

https://react-magma.cengage.com/version/4.5.0/api/pagination/

### Issue:
The aria-current attribute is set to "true" to represent the currently selected page in the pagination navigation. This represents the current item within a set, but setting the value to "page" would represent the current page within a set of pages, which is more appropriate in this case.

### Suggestion:
Consider using aria-current="page" instead of aria-current="true" for the selected pagination control.

**Comment by chris-cedrone-cengage** [comment]
_-Verify the use of aria-current_ ✅
_-Verify that aria-label is visible on the nav property_ ✅

All set
