### ISSUE TITLE
Loading indicator on buttons

### ISSUE THREAD

**Issue by joasmi723** [cengage/react-magma#139]
**Description**
**Purpose**: For buttons that submit data like Save, Submit, etc., we need to provide feedback that it's working.

**inVision:** https://cengage.invisionapp.com/share/YG10B6KE5J8P
**Inspect:** https://cengage.invisionapp.com/d/main#/console/15897083/386655945/preview

1. When button is triggered, the button changes to disabled.  However, the spinner is not the color of disabled text.  It is neutral03 (#727272) or white depending on the original button or inverse state.
2. The content of the button is replaced by a center-aligned loading spinner.
3. Sizes
         Large = 28px
         Medium = 20px
         Small = 12px
4. During all of these transitions, the width of the button should stay the same as it was in its original state.
5.  If there's an error while submitting, the button should change back to its original state and a separate error message would be displayed somewhere
6. If the process is successful, then the success will be indicated with some form of alert or confirmation.

Accessibility
1. When loading, I believe we should announce this to the screen reader.

**Comment by avanslaars** [comment]
Working on this one with Jamie and wanted to clarify the requirements a bit.

1. For points 5 and 6, the setting and resetting of whether or not to show the loading indicator should be controlled via prop and this will fall to the consumer. We have no way of knowing the state of an external process from within the button. We're going to control this with an `isLoading` prop that the consumer will pass in and update as appropriate.
2. "it is neutral03 (#727272) or white depending on the original button or inverse state." - I think there will be more factors here... the disabled color of a button doesn't appear to change based on the `isInverse` prop, so we'll need to consider the color, variant, etc. We'll follow the attached designs as a guide.
