### ISSUE TITLE
A11y: Dropdown - active item index issue

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1439]
CENG_1486

https://react-magma.cengage.com/version/4.5.0/api/dropdown/#active_item_index

![image](https://github.com/user-attachments/assets/a561bb6e-be9c-4baf-a6b3-2e0c1c87f3c3)

**Issue description:**
The Active Item Index menu has a selected option that is indicated with a checkmark. The selected state of this option is not communicated programmatically.

**Solution:**
Use aria-selected="true" on any option that is selected within this menu.

**Comment by chris-cedrone-cengage** [comment]
`aria-current="true"` appears accordingly in the example properly within:
