### ISSUE TITLE
Deprecate patterns and schema-renderer packages

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1498]
These packages do not get any usage, and we have no plans to add to them. We should deprecate them.

**Comment by chris-cedrone-cengage** [comment]
Marked as deprecated on README ✅
Added an alert(banner?) on the docs site ✅
Deprecated them on npmjs ✅
In addition, there were a few other old magma packages that have hung around for a while that we don't even have the source code for, so I marked those as deprecated on NPM as well. ✅
