### ISSUE TITLE
Chore: Improve TypeScript, Linting, and Styling Support in MDX Files

### ISSUE THREAD

**Issue by moathabuhamad-cengage** [cengage/react-magma#1553]
Description: We need to ensure MDX files have proper TypeScript support, apply linting rules, and have consistent styling.
This task involves investigating current issues, updating configurations, and testing changes to improve developer experience and reduce bugs in documentation code examples.

**Comment by chris-cedrone-cengage** [comment]
I noticed a missing margin with the header for each component page:

Bug:
<img width="1573" alt="Needs margin" src="https://github.com/user-attachments/assets/ce7cb37a-248e-43cf-93aa-496d0ae26b03" />

Latest on [dev](https://next--upbeat-sinoussi-f675aa.netlify.app)
<img width="1573" alt="OG margin" src="https://github.com/user-attachments/assets/e01a3832-32e8-40f0-8f09-a626035f91af" />

**Comment by moathabuhamad-cengage** [comment]
@chris-cedrone-cengage this was an intended change in #972 in 
`website/react-magma-docs/src/components/LayoutComponent/index.js`
