### ISSUE TITLE
Toggle Button Group: `enforced` and `exlusive` props do not behave as expected

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1565]
**Component:**
Toggle Button Group

**Description:**
The "Enforced" and "Exclusive" properties on this component are no longer working properly. It is working fine in 4.6.

**Steps to reproduce:**

- Navigate to https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/togglebuttongroup--alignment-example
- Try turning these two options on separately and also together and you'll see they aren't working.
- Enforce means after the initial selection, at least one button has to be selected
- Exclusive means only one button can be selected at a time

**Can it only be reproduced in dev or is it reproducible in the last released version?**
Only on dev

**Comment by nikitaorliak-cengage** [comment]
Cases that have been tested:

- Check the logic for __Toggle Button Group__ without props;
- Check the logic for __Toggle Button Group__ with the `enforced` prop;
- Check the logic for __Toggle Button Group__ with the `exclusive` prop;
- Check the logic for __Toggle Button Group__ with the `enforced` and `exclusive` props;
- Check all the previous cases with a screen reader.
