### ISSUE TITLE
Search: MAST search input is not filling the entire width anymore

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1593]
**Describe the bug**
MAST uses Search inside the GroupButton. It used to fill the width of the screen with version 4.6.0 but does not with the prerelease version.

Firstly, the input doesn't fill the entire existing width (it just doesn't have width: 100%), so their search is smaller than it should be. It was fine in previous versions.
Secondly, after the Search there is an empty block (about 8px), which doesn't allow to fill the whole existing width, it just takes a small space.

**Additional Context**
I also couldn’t replicate this, she showed me this a few weeks ago. https://codesandbox.io/p/sandbox/mast-buttongroup-l865pt?file=%2Fexample.tsx. 

The changes introduced that could potentially be related are:
- [482268a](https://github.com/cengage/react-magma/commit/482268a7ece77cd3927265d131d7eaf368983831): fix(Input): Remove flex-shrink to allow inputs to shrink as needed.
- [fbae9ce](https://github.com/cengage/react-magma/commit/fbae9ce39862636d826da2f1854371887cd3aca1): fix(Input): Style update: Fix HelpLink position on inputs.
- [d8662d6](https://github.com/cengage/react-magma/commit/d8662d6f68c9c3d801a840b659b18c94ecced813): feat(Input): Update Input additional children position based on label position.

**Comment by nikitaorliak-cengage** [comment]
The issue was fixed on the MAST branch.
