### ISSUE TITLE
Toast / Auto-dismiss - Have to click twice to dismiss

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#240]
Looks like this bug was introduced in 2.3.10.

The problem appears to only exist on toasts that auto-dismiss.  You have to click twice to manually dismiss.  The first click only puts focus on the dismiss button.

**Comment by jamiesmyln** [comment]
This has something to do with the browser cache - I think - since a hard refresh fixes the problem and we are already handling state properly. It's difficult to reproduce.

**Comment by rcgillet** [comment]
Fixed in version 2.5.1 along with another `StyledButton` change.
