### ISSUE TITLE
Add icons to the RM icon library

### ISSUE THREAD

**Issue by amytaros** [cengage/react-magma#255]
Google has added some icons that I would like to use. Could we add them to the RM icon library?

[dark_mode.svg.zip](https://github.com/cengage/react-magma/files/6428494/dark_mode.svg.zip)
[light_mode.svg.zip](https://github.com/cengage/react-magma/files/6428496/light_mode.svg.zip)

**Comment by orion-cengage** [comment]
These are new icons specifically for dark and light modes.  I'll get them added.

**Comment by orion-cengage** [comment]
I'm going to "upgrade" this ticket to include all of the new icons from Material Icons 4.0

**Comment by orion-cengage** [comment]
These icons along with a ton of others have been added to React Magma and were released in 2.4.
