### ISSUE TITLE
Bug:  Escape key closes all modals when modals are nested

### ISSUE THREAD

**Issue by joasmi723** [cengage/react-magma#264]
**Describe the bug**

If a user opens up a modal from within another modal, the modals stack on top of one another.  When you press the escape key to close the top modal, this closes all open modals, not just the one on top.

This is a particular issue when you put a datepicker in a modal, and open the Help modal from there.

**To Reproduce**
1. Go to sandbox here:  https://codesandbox.io/s/react-magma-example-forked-kg2jx?file=/example.tsx
2. Click on 'Show Modal'
3. Scroll down to Datepicker.  Open calendar widget.  Press ? key.  Press ESC key.
4. All modals (including the one containing the datepicker) close.

**Expected behavior**
Expected that only the top modal (in this case the date picker help) closes.

**Comment by aaronmaturen** [comment]
add to #397

**Comment by silvalaura** [comment]
Triple check with the a11y channel that closing one dialog at a time is the expected behavior for users.

**Comment by silvalaura** [comment]
**QA Notes:**
- When there are 2 stacked modals, pressing ESC closes one at a time ✅
- When there is a DatePicker inside a modal while a date has not been selected, pressing ESC closes only the date picker panel ✅
- When there is a DatePicker inside a modal while a date has been selected, pressing ESC closes only the date picker panel 🚫 **the modal closes in addition to the panel**
- When there is a Dropdown inside a modal, pressing ESC closes only the dropdown panel ✅
- When there is a Combobox inside a modal, pressing ESC closes only the combobox panel ✅
- When there is a Multi Combobox inside a modal, pressing ESC closes only the combobox panel ✅
- When there is a Select inside a modal, pressing ESC closes only the select panel ✅
^ these behaviors were both tested on a modal and also on a modal inside another modal

Known issue that we will deal with in a separate ticket:
- When pressing ESC on Combobox & Multi Combobox, it takes tabbing twice to get to the next element

**Comment by orion-cengage** [comment]
I tested using Laura's notes above, specifically bullet 3. I believe it is working as expected.
