### ISSUE TITLE
Сan't remove value in DatePicker if it was already set once time

### ISSUE THREAD

**Issue by Maks19** [cengage/react-magma#266]
We can't remove value in **`DatePicker`** if it was already set once time.

Sandbox example - https://codesandbox.io/s/react-magma-example-forked-6ennh?file=/example.tsx:334-343

**Comment by rcgillet** [comment]
For this we should probably add an `isClearable` prop to the `InputBase` component that adds a clear icon to the right of the input and is used to empty out the value. This functionality can then be used in any `input` fields we have in the future. 

Things to consider: 
 - controlled vs. uncontrolled changing of value. (what state the current input is in)
 - custom clear icons
 - clear icon placement in an input that has another icon in it (i.e. Search component)
