### ISSUE TITLE
Add support for 'DD/MM/YYYY' format to Datepicker

### ISSUE THREAD

**Issue by Brazhko** [cengage/react-magma#295]
**Datepicker** component doesn't support '_DD/MM/YYYY_` format even if **I18nContext** object is changed ({"locale": enAU,  "dateFormat": "dd/MM/yyyy"}) - '_onBlur_' event handler resets value in the input or swaps day and month values.

Sandbox - https://codesandbox.io/s/react-magma-example-forked-4j57k?file=/example.tsx

**Comment by silvalaura** [comment]
Duplicate of #748

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast: http://somup.com/c3jQQRuJKe
Thanks!

**Comment by Uditsingh67** [comment]
Issue does not exist.
See Screen-cast : http://somup.com/c3jwivU2TR
