### ISSUE TITLE
A11y: Long value of a dropdown menu item is read as 2 menu items by screen reader

### ISSUE THREAD

**Issue by EleanorKartyshova** [cengage/react-magma#296]
Long value of a dropdown menu item is read as 2 menu items by screen reader

**Pre-conditions:**
there is a long value in the dropdown menu item

**Steps to reproduce the behavior:**
1. Launch the screen reader
2. Navigate by the menu items using  up/down arrow keys 
3. Listen to announcing the long menu item value

**Expected behavior:**
Value is read as 1 menu item

**Desktop:**
windows10/chrome 91/nvda

![photo_2021-06-23_12-16-03](https://user-images.githubusercontent.com/72541410/123071978-cccc1900-d41d-11eb-9ef1-ff7cc9cd70c1.jpg)

**Comment by ccedrone** [comment]
Could not reproduce this behavior while testing in Windows 10 with NVDA. It's properly highlighted then dictated as usual with the program.

This may be a disconnect since I used a virtual machine to replicate the issue. Please verify.

**Comment by hkrishna29** [comment]
https://user-images.githubusercontent.com/90398760/222519250-dd9c6c0d-eb56-4f67-a59f-8cc48656585d.mp4

**Comment by hkrishna29** [comment]
After reading the first option the Screen reader render the verbiage ' 1 of 2' after reading the second option it renders '2 of2'  .

**Comment by ccedrone** [comment]
The original comment was mentioning how the first of the two options was broken in half. What you captured is expected behavior.
