### ISSUE TITLE
In Firefox the animation in buttons is absent when you press the Space key to activate the button

### ISSUE THREAD

**Issue by EleanorKartyshova** [cengage/react-magma#315]
**Steps to reproduce the behavior:**
1. Go to https://react-magma.cengage.com/version/2.3.12/api/dropdown/
2. Click on the first dropdown button 2 times
3. Press the Space key on the dropdown button 2 times
4. Pay attention to the button

**Expected behavior**
The animation in the button is present

**Desktop:**
 - Windows 10
 - Firefox 89.0

**Additional context**
The animation isn't displayed on any buttons, dropdown buttons, icon buttons

https://user-images.githubusercontent.com/72541410/125260365-f08dcb00-e308-11eb-867a-0bc2c5799394.mp4

**Comment by jamiesmyln** [comment]
Verified the issue. I spent some time trying to figure out the cause and I can't track it down. Our usage for Firefox compared to Chrome is low and the focus behavior is not impeded so we won't be spending more time on this issue.
