### ISSUE TITLE
react-magma-docs - Update display of props

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#317]
This update is only for the new version 3 of the React Magma docs.

**Purpose:** The props are currently displayed in tables, and due to the content of these tables, they aren't providing a very good experience on anything other than the largest of screens.  We're going to try a new approach.

**Figma:** https://www.figma.com/file/pdcWRIHYjeu8y09XzAT1SB/React-Magma-Docs?node-id=17%3A12983

### AC's

- Each prop will get its own two-column layout.
-- Start with the prop name
-- Two-column section consists of the attribute title on the left (Type, Default, Description) and the full details of that attribute on the right.
![image](https://user-images.githubusercontent.com/24397282/183144109-01fe0519-8d6a-4869-b273-494103e61226.png)

- Required props called out with **small primary tag** instead of the previous asterisk method.
![image](https://user-images.githubusercontent.com/24397282/183144215-ba2a7213-1d5c-4aaa-a739-323f6997f669.png)

- I'm hoping we can keep this same two-column layout all the way down to 320px - 375px.  We might need to tweak once we see it in action.
![image](https://user-images.githubusercontent.com/24397282/183421586-a91eba8e-0a02-447b-8393-b33e021008bf.png)

-- It's possible we may need to go to a single column layout on small screens.
![image](https://user-images.githubusercontent.com/24397282/183421704-5e5bbd06-cdf4-468b-98c7-3cf520bc297c.png)

**Comment by jamiesmyln** [comment]
This is ready on feature/docs-props-table but we're waiting to merge it until v3 is ready for it.
