### ISSUE TITLE
RM 3 (4) - New home page

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#318]
This ticket is only for the new version 3 of the React Magma docs.

New home page to go with the rest of the updates.  Designed to inform visitors more efficiently and accurately about what React Magma is and how to get started, and designed with future Dark Mode in mind.

**inVision:** https://cengage.invisionapp.com/share/Z3RH81FTNMC

### AC's

- Not much in terms of functionality.  The copy and design can be pulled from the inVision prototype.
- Designing and Developing sections have buttons leading to the pages to get started
-- Start Designing: links to "Getting Started" page under "Designing" section.
-- Start Developing: links to "Getting Started" page under "Developing" section.
- Responsive behavior (see prototype)
-- 768px wide and below, the Designing and Developing sections stack
-- 600px wide and below, the Feature cards stack on top of each other
-- Might have to make some other tweaks at other breakpoints based on what happens to the content.

### RM Logo
[rm-logo-large.png.zip](https://github.com/cengage/react-magma/files/6810893/rm-logo-large.png.zip)

### Screenshot

![image](https://user-images.githubusercontent.com/24397282/125480502-2c348960-8fef-4ccf-9027-073a93be8c69.png)

**Comment by silvalaura** [comment]
This work was merged in https://github.com/cengage/react-magma/pull/352 and then reverted https://github.com/cengage/react-magma/commit/0f60e622b6578c20be1078645176a3153cd856a6. Not sure why, but we can certainly use this as a starting point.
