### ISSUE TITLE
Component Update: Progress bar

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#327]
**Purpose:** Update styling of the progress bar for better consistency with other RM components and improved visual design.

**inVision:** https://cengage.invisionapp.com/share/CJ11FQNHAPW2

- See inVision for new styling specifics for both light and dark backgrounds (inverse)
![image](https://user-images.githubusercontent.com/24397282/127006691-456f1948-9f74-435c-9c24-e40af81d434f.png)

![image](https://user-images.githubusercontent.com/24397282/127006719-e7440377-2218-4d22-9f04-dfe3b14677e3.png)

- Verify the progress bar has rounded ends
- Verify there one size of progress bar (8px tall) but we don't stop someone from being able to make it taller or shorter.
- Verify there are now 3 standard colors to choose from
-- primary, danger, success
![image](https://user-images.githubusercontent.com/24397282/127006929-96b6c1b3-a9aa-4c63-846d-1543910a003d.png)

- Verify we use our new inverse colors for the inverse version
![image](https://user-images.githubusercontent.com/24397282/127007051-4d64aea5-4be7-48b1-ba93-86a00d8bffe1.png)

**Comment by silvalaura** [comment]
Relates to https://github.com/cengage/react-magma/issues/64

**Comment by silvalaura** [comment]
I think this has been completed indirectly with the progress bar issue in the redesign. @orion-cengage do you mind reviewing it and updating this with anything missing, or closing this if done?

https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/progressbar--default

**Comment by orion-cengage** [comment]
This issue is now unnecessary as we have made the necessary updates for new branding in RM3.
