### ISSUE TITLE
fix: update toast test to modern jest timers

### ISSUE THREAD

**Issue by aaronmaturen** [cengage/react-magma#337]
In Toast.test.js we have `jest.useFakeTimers('legacy');` that should ultimately be updated to `jest.useFakeTimers();` to use the modern timers. 

Unfortunately there is something in the toasts that causes side effects outside of each individual test. This may be the `setInterval` in the ProgressBar that's used by AlertBase 🤔

**Comment by silvalaura** [comment]
I don't see any reference to `jest.useFakeTimers('legacy');` in the code base, so closing this issue.
