### ISSUE TITLE
New: Page layout templates

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#370]
**Purpose:** Create a selection of pre-defined page templates for easy re-use and consistency.

**inVision:** https://cengage.invisionapp.com/share/EQ11QO66V52Z

- Each template is going to be set up with 3 possible pre-determined screen regions: Header, Left sidebar, Main Panel
- Each template should have the header component in place, and the consumer can configure the header to fit their needs.
- **Full-Width Template**
-- Header extends all the way to the edges of the browser
-- Main Panel - Max-width of 1600px, centered within the browser window, 24px margins
--- Technically this won't appear as full-width on extremely large screens.
![image](https://user-images.githubusercontent.com/24397282/133456775-d2154ce8-c2b7-47d2-ac0c-16a2e90a98a7.png)

- **Restricted-Width Template**
-- Header extends all the way to the edges of the browser
-- Main Panel - Max-width of 1152px, centered within the browser window, 24px margins.
-- The main panel area doesn't start getting smaller until the browser window gets too small to support that width.
![image](https://user-images.githubusercontent.com/24397282/133456879-36c4a470-546e-4988-aab5-d8e919946d8c.png)

- **Sidebar Templates**
-- Left Sidebar set at 240px wide
-- Full Header with Sidebar
--- Header extends all the way left edge of the browser to the right edge.
-- Partial Header with Global Sidebar
--- Sidebar goes all the way to the top of the browser, and the Header area starts on the right edge of the Sidebar.
-- Main Panel - Choice of full-width content area or restricted-width content area (max-width 1152px)
![image](https://user-images.githubusercontent.com/24397282/133457147-040a317e-ac1c-471f-8223-530f2229a073.png)
![image](https://user-images.githubusercontent.com/24397282/133457912-df28ccbe-1c9a-4a50-acf1-bc3e5e1dc84b.png)

### Responsive Behavior
- Templates without Sidebar
-- 600px wide and below - Header changes to compact
- Templates with Sidebar
-- 1024px wide and below, the left sidebar is suppressed and is instead opened in a drawer from a menu button on the left side of the header.
-- 600px wide and below - Header changes to compact

### Special Exceptions
- Pages with CU Sidebar
-- The CU Sidebar is a bit different because it also has a minified or icon-only view it can be collapsed down to.
-- Differences in responsive behavior
--- 1024px wide and below, the sidebar is displayed automatically in its icon-only view and when you expand it, it overlays the content of the page instead of pushing it to the right.
--- 600px wide and below, the sidebar is removed and replaced with a menu button on the left side of the header and opens in a drawer.
![image](https://user-images.githubusercontent.com/24397282/133469405-e7cbfea7-0c48-4398-98cc-0e7c0d6808b6.png)
![image](https://user-images.githubusercontent.com/24397282/133469465-b0fa416c-179c-46aa-a5e4-9dfa0c34acc0.png)
![image](https://user-images.githubusercontent.com/24397282/133469520-b29777bb-d81e-4238-9c89-c75df0e2e3a8.png)

- Need to be able to support layouts where backgrounds extend all the way to the edges of the browser, but the content within adheres to the columns.
![image](https://user-images.githubusercontent.com/24397282/133472259-1f663476-9e65-4b2f-8121-fa2d79f00f14.png)

**Comment by silvalaura** [comment]
@ccedrone @orion-cengage I'm unsure about this issue-- has it been completed? If not, what's missing?

https://react-magma.cengage.com/version/3.1.0/api-intro/page-templates/

**Comment by ccedrone** [comment]
This ticket was completed via: https://github.com/cengage/react-magma/pull/422

**Comment by silvalaura** [comment]
If all the requirements have been met, we should close it. I'm just wondering why it's under `On Hold`

**Comment by ccedrone** [comment]
I believe additional templates outside of this ticket were to be made, however after gauging interest, it went stale. This part of the work however was completed.

**Comment by silvalaura** [comment]
Remaining work:
```
(Orion) I took a look at the [Page Templates](https://react-magma.cengage.com/version/3.1.0/api-intro/page-templates/) in RM and it looks like on the surface we’re covering all of the templates I had specced out and requested in this issue.

What I don’t know how to do is actually test them out.  To see how easy they are for a developer to use, customize, and to verify all of the built-in Responsive behavior actually works.

Any ideas how we can do this?  Like, could one of you actually create some “test” pages somewhere using the templates, put in some fake content, and then we can see them running in a browser?

```

**Comment by Uditsingh67** [comment]
Verified the ticket and found fixed.
**See Screen-cast :** http://somup.com/c36FetvbhW
Thanks!
