### ISSUE TITLE
Fix letter-spacing on 12px and 14px text

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#385]
**Purpose:** 12px and 14px text are supposed to have letter-spacing applied to them, automatically where possible.

14px = .16px letter-spacing
12px = .32px letter-spacing

### Places to update
- Typography system
-- We have several pre-made text styles that use 12px and 14px size fonts.  We need to apply the letter-spacing here.
--- Don't forget that a lot of these styles change when the devices gets smaller.
- All other components - We need to hunt down all other instances within our components where 14px and 12px font-sizes are used.  If they aren't using the pre-made font styles and therefore inheriting the correct letter-spacing, then we either need to update the component to use the pre-made styles, or manually add the correct letter-spacing to them.
-- Examples: small buttons, helper text and error text on inputs

**As individual components are updated, please make a list of them so they can be more easily tested in the eventual PR.**

**Comment by ccedrone** [comment]
See pull request: https://github.com/cengage/react-magma/pull/386
