### ISSUE TITLE
Alert component - missing padding

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#387]
The alert component is missing the 12px of padding on the right side, which can result in the text touching the right edge of the alert.  The issue appears to be isolated to the Alert component and not the Banner or Toast.

![image](https://user-images.githubusercontent.com/24397282/136398474-b78f8cc2-c8bc-46b1-87ae-8c17781efaf4.png)

![image](https://user-images.githubusercontent.com/24397282/136398678-4049a46f-ddb5-4829-927c-15324b34f0a1.png)

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : <<https://www.screenpresso.com/=d3hjf>>
Thanks!
