### ISSUE TITLE
"Check out this PDF" link in "Contribution Guidelines" page is not working

### ISSUE THREAD

**Issue by hkrishna29** [cengage/react-magma#391]
**Describe the bug**
"Check out this PDF" link  in "Contribution Guidelines is not displaying 'Not Found' page

**To Reproduce**
- Launch https://react-magma.cengage.com/
- Click on 'View Latest Version' button 
- Click on 'Contribution Guidelines' link
- Click on 'Check out this PDF' link

**Expected behavior**
Pdf document should be displayed.

**Screenshots**
https://screencast-o-matic.com/watch/cr6jD0VXFWn

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [chrome]
 - Version [94.0.4606.81(64-bit)]

**Comment by silvalaura** [comment]
This has been fixed indirectly: https://react-magma.cengage.com/version/2.5.13/downloads/contributing-to-react-magma.pdf
