### ISSUE TITLE
Tag Update: Add success and danger variations

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#398]
**Purpose:** The UX Team has proven the need for the success and danger variants within the tag component.  We also need a min-width added to the tags to improve the presentation of tags with very short labels.

**inVision:** https://cengage.invisionapp.com/share/4311WPW1JF5K

### Acceptance Criteria

- Min-width
-- Add a min-width of 64px to the default size Tag
-- Add a min-width of 48px to the small size Tag
- For the Color options, add the following:
-- **Success**
--- background color = success (#3A8200)
--- inverse background color = successInverse (#91CF60)
-- **Danger**
--- background color = danger (#C61D23)
--- inverse background color = dangerInverse (#F59295)

![image](https://user-images.githubusercontent.com/24397282/138471926-727eb1cc-a91c-46a5-bc02-45ccb5c7af09.png)

**Comment by ccedrone** [comment]
PR: https://github.com/cengage/react-magma/pull/409
