### ISSUE TITLE
Docs bug: Table pagination

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#400]
**Describe the bug**
Bug is located in the pagination section of the Table component: https://react-magma.cengage.com/version/2.5.5/api/table/#pagination

Something weird going on with the results per page label

**Screenshots**
![image](https://user-images.githubusercontent.com/24397282/138952509-19bee56e-0876-4e48-87db-ff9ceba741e8.png)

**Comment by Uditsingh67** [comment]
The issue is fixed.
RM Link : [https://next--upbeat-sinoussi-f675aa.netlify.app/api/table/#pagination](url)
See Screen-cast: <<http://somup.com/c3iFfQuYYq>>
Thanks!
