### ISSUE TITLE
"Scatter point"  value does not change upon updating the data from 'Controls' 

### ISSUE THREAD

**Issue by hkrishna29** [cengage/react-magma#407]
**Describe the bug**
When data is modified by using 'Controls'  option , it is not reflected in  "scatter point" value

**To Reproduce**
1. Launch https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/chart--default
2. Select the default chart 
3. Click on the chart tab
4. Press 'A' key
5. Click on the Controls tab
6. Click on the 'data' node
7. Click on the node '0'
8. Click on the node 'data'  
9. Click on the node '0'
10. Change the 'Y-Axis' value 
11. Observe the change in the graph
12. Now hover the cursor over the 'Scatter point' of the newly updated data
13. Verify the "scatter point" value not updated

**Expected behavior**
When data is modified by using 'Controls'  option , it should be reflected in "scatter point" value

**Screenshots**
https://www.screenpresso.com/=0xyNd

**Desktop (please complete the following information):**
 - Windows 10 : Chrome [ 95.0.4638.69] /Edge [ Version 95.0.1020.40]
 - Mac 14 : Safari [14.1.2]
 
**Additional context**

**Comment by Uditsingh67** [comment]
The issue **no more reproducible**.
See screen-cast : https://www.screenpresso.com/=CoOTb
Thanks!
