### ISSUE TITLE
New component: Blockquote

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#414]
Purpose: Create new Blockquote component

InVision: https://cengage.invisionapp.com/share/GM123CETDTN4

![image](https://user-images.githubusercontent.com/24397282/144275633-84d3b852-d617-4c9e-b84f-876a791e78d8.png)

### AC
- Content
-- Able to provide the quote (required)
-- Able to provide source attribution (optional)
- Style
-- Default styles
--- Quote = body/large, productive font style
--- Source attribution = body/medium, productive font style, subdued color
--- Bar on the left
---- 4px wide, background-color = #DFDFDF
--- Padding = 12px top/bottom, 16px left/right
-- Able to customize the type style of both quote and source attribution, including changing to Expressive or Narrative
-- Able to customize the color of the bar
- Inverse
-- Provide default inverse version as well.

![image](https://user-images.githubusercontent.com/24397282/144275722-297d6778-812b-4ebf-914c-331ce6722758.png)

**Comment by ccedrone** [comment]
See: https://github.com/cengage/react-magma/pull/426
