### ISSUE TITLE
The maximum value of conversion rate is not getting altered if we increase the annual sales figure to a greater value

### ISSUE THREAD

**Issue by Uditsingh67** [cengage/react-magma#415]
**To Reproduce**
1. Launch https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/chart--default
2- Click on the chart
2- select the default chart
3-Click on the chart tab
4-Press 'A' key
5- Click on the Controls tab
6- navigate to componentProps
7-Click on the Y axis
8- click on the tickValues
9-Change the value and observe

</body>
</html>

**Expected behavior**
The maximum value of conversion rate should get altered if we increase the annual sales figure to a greater value.

**Screenshots**
https://www.screenpresso.com/=EPGub

Desktop (please complete the following information):

Windows 10 : Chrome [ 95.0.4638.69] /Edge [ Version 95.0.1020.40]
Mac 14 : Safari [14.1.2]

**Additional context**

**Comment by rcgillet** [comment]
If you change the tick values, you must also change the `domain` prop.

Not an issue.
