### ISSUE TITLE
Documentation> Checkbox link> "Not Found" error message is appearing upon launching

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#462]
**Describe the bug**
"Not Found" error message is appearing upon launching the link "Checkbox".

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api-intro/custom-styles/#style_props_for_complex_components
2. Click on "Checkbox" link
3. Verify the message

**Expected behavior**
Appropriate page should appear upon launch the link.

**Screenshots**
https://somup.com/c3nQ2tZNst

**Desktop :**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=1HQK
Thanks!
