### ISSUE TITLE
Documentation> Changelog 2.3.0 (2020-12-08)> Unable to navigate by clicking on "2.3.0 (2020-12-08)" present in left panel.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#463]
**Describe the bug**
Heading "2.3.0 (2020-12-08)" is not appearing in right side at top when clicks on "2.3.0 (2020-12-08)" present in left panel.

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/
2. Navigate to "Changelog"
3. Click on "2.3.0 (2020-12-08)"
4. Verify that navigation is not working

**Expected behavior**
Heading "2.3.0 (2020-12-08)" should appear in right side at top when clicks on "2.3.0 (2020-12-08)" present in left panel.

**Screenshots**
https://somup.com/c3n61nZPVR

**Desktop :**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by greenervigil** [comment]
please retest

**Comment by Uditsingh67** [comment]
The issue is still reproducible
See Screen-cast : http://somup.com/c3XeeTvgSF
Hence, Reopening the ticket.
Thanks!

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : http://somup.com/c3XXhzv7C3
Thanks!
