### ISSUE TITLE
Documentation> Custom Items> Link "using your custom type." is navigating to incorrect location

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#464]
**Describe the bug**
Link "using your custom type." is navigating to "Async" heading.

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api/combobox/#custom_items
2. Navigate to "Custom Items"
3. Click on link "using your custom type."
4. Observe that heading "Custom Items Typescript" is appearing for fraction of seconds
5. Verify that heading "Async" is appearing after some time

**Expected behavior**
Link "using your custom type." should navigate to correct location.

**Screenshots**
https://somup.com/c3n66ZZPFg

**Desktop :**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by greenervigil** [comment]
could not recreate, please re-test to verify.

**Comment by Uditsingh67** [comment]
The issue is Fixed.
See Screen-cast : http://somup.com/c36IhUv6Hn
Thanks!
