### ISSUE TITLE
Documentation> "View Design Guidelines" button> "Not Found" error message is appearing upon clicking the button "View Design Guidelines"

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#466]
**Describe the bug**
"Not Found" error message is appearing upon clicking the button "View Design Guidelines".

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api/form/
2. Click on "View Design Guidelines" button
3. Verify the error

**Expected behavior**
Appropriate page should appear upon clicking the button "View Design Guidelines"

**Screenshots**
https://somup.com/c3n6XdZPOe

**Desktop :**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
"View Design Guidelines" button is not appearing in Form page.
Form Link : https://next--upbeat-sinoussi-f675aa.netlify.app/api/form/
**See Screen-cast :** https://www.screenpresso.com/=zJk9c
Hence, Reopening the ticket.
Thanks!

**Comment by silvalaura** [comment]
Functioning as designed. There is no Form design page.
