### ISSUE TITLE
Documentation_Checkbox> "Not Found" error message is appearing upon clicking the link

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#467]
**Describe the bug**
"Not Found" error message is appearing upon clicking the link "Checkbox".

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api/formgroup/
2. Click on "Checkbox" link
3. Verify the error

**Expected behavior**
Appropriate page should appear upon clicking the link "Checkbox".

**Screenshots**
https://somup.com/c3n6X9ZPOA

**Desktop :**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=86DDd
Thanks!
