### ISSUE TITLE
Documentation> Render Props Google button> "Not Found" error message is appearing upon clicking the button

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#468]
**Describe the bug**
"Not Found" error message is appearing upon clicking the "Render Props Google" button.

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api/hyperlink/#render_props_usage
2. Click on "Render Props Google" button
3. Verify the message

**Expected behavior**
Appropriate page should appear when clicks on  "Render Props Google" button.

**Screenshots**
https://somup.com/c3nXQqZRcr

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=DV3Bc
Thanks!
