### ISSUE TITLE
react-magma-docs: Better 404s

### ISSUE THREAD

**Issue by aaronmaturen** [cengage/react-magma#47]
We need a more "on brand" 404 page 

https://react-magma.cengage.com/blargh

packages/react-magma-landing/static/404.html

**Comment by orion-cengage** [comment]
We can use the current design for the 404 page content component.  It's not final yet, but should work for the interim.

**inVision:** [https://cengage.invisionapp.com/share/MPZVZ3T6EHS](https://cengage.invisionapp.com/share/MPZVZ3T6EHS)

![RM Docs - 404 - Large](https://user-images.githubusercontent.com/24397282/104213310-c14edd80-53fb-11eb-83ef-f537faa59504.png)
![RM Docs - 404 - Medium](https://user-images.githubusercontent.com/24397282/104213314-c1e77400-53fb-11eb-951a-95095fe77fb4.png)
![RM Docs - 404 - Small](https://user-images.githubusercontent.com/24397282/104213316-c2800a80-53fb-11eb-8e4e-fd62f4195ac7.png)

**Comment by aaronmaturen** [comment]
I think we technically have two 404 pages... 

There's the one inside gatsby that will get hit for `/version/next/doot` https://react-magma.cengage.com/version/next/doot
And then there's the one from netlify that gets hit for `/doot` https://react-magma.cengage.com/doot

**Comment by orion-cengage** [comment]
The same content should be used for both

**Comment by silvalaura** [comment]
**How to test**
- Check the docs site:
-- https://next--upbeat-sinoussi-f675aa.netlify.app/404 or any random string instead of "404"
- The landing page wont be testable until it's released, so skip this.

**Comment by Uditsingh67** [comment]
@silvalaura 
Not able to find "Sorry, page not found."
Please Provide Steps/URL

**Comment by silvalaura** [comment]
> @silvalaura Not able to find "Sorry, page not found." Please Provide Steps/URL

**How to test**
- Verify the docs site:
-- https://next--upbeat-sinoussi-f675aa.netlify.app/404 or any random string instead of "404"
- Verify the landing page:
-- https://react-magma.cengage.com/404 or any random string instead of "404"

**Comment by Uditsingh67** [comment]
We have verified this ticket and found that this ticket is working as expected.
**See Screen-cast :** http://somup.com/c36qfPvFRg
Thanks!
