### ISSUE TITLE
Documentation> "MAIN PAGE", "FAQ", "ABOUT US" button> "Not Found" error message is appearing upon clicking the button

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#470]
**Describe the bug**
"Not Found" error message is appearing when clicks on "MAIN PAGE", "FAQ", "ABOUT US" button.

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api/nav-tabs/#custom_component
2. Click on MAIN PAGE", "FAQ", "ABOUT US" button
3. Verify the error 

**Expected behavior**
Appropriate page should appear when clicks on "MAIN PAGE", "FAQ", "ABOUT US" button.

**Screenshots**
https://somup.com/c3nX6kZR16

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=YXWFc
Thanks!
