### ISSUE TITLE
Documentation> Input link> "Not Found" error message is appearing upon clicking the link

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#473]
**Describe the bug**
"Not Found" error message is appearing upon clicking the link "Input".

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api/search/
2. Click on "Input" link
3. Verify the error

**Expected behavior**
Appropriate page should appear upon clicking the link "Input".

**Screenshots**
https://somup.com/c3nXl1ZRly

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=MsB9c
Thanks!
