### ISSUE TITLE
Documentation> "Legacy Select" link> "Not Found" error message is appearing upon clicking the link 

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#474]
Describe the bug
"Not Found" error message is appearing upon clicking the link "Legacy Select".

To Reproduce

1. Go to https://react-magma.cengage.com/version/2.5.7/api/select/#basic_usage
2. Click on "Legacy Select " link
3. Verify the error

Expected behavior
Appropriate page should appear upon clicking the link "Legacy Select".

Screenshots
https://somup.com/c3nXlIZRIQ

Desktop:

OS: [Win 10]
Browser [chrome]
Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
"Legacy Select" link is displaying as plain text in Selects page.
Selects Link : https://next--upbeat-sinoussi-f675aa.netlify.app/api/select/
**See Screen-cast :** https://www.screenpresso.com/=Q5FG
Hence, Reopening the ticket.
Thanks!

**Comment by greenervigil** [comment]
The link is no longer needed.  Please verify "legacy Select" is text only.

**Comment by Uditsingh67** [comment]
The issue is **fixed**.
**See Screen-cast :** http://somup.com/c36Ihrv6mB
Thanks!
