### ISSUE TITLE
Documentation> "stateChangeTypes" link> Link "stateChangeTypes" is navigating to incorrect location

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#475]
Describe the bug
Link "stateChangeTypes" is navigating to heading "Internationalization" instead of heading "State Change Types"

To Reproduce

1. Go to https://react-magma.cengage.com/version/2.5.7/api/select/#generic_state_change
2. Click on "stateChangeTypes" link
3. Verify that link is navigating to heading "Internationalization"

Expected behavior
Link "stateChangeTypes" should navigate to correct location.

Screenshots
https://somup.com/c3nXlYZRIG

Desktop:

OS: [Win 10]
Browser [chrome]
Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by greenervigil** [comment]
Could not recreate.  Please retest.

**Comment by Uditsingh67** [comment]
The Issue is still reproducible.
See Screen-cast : http://somup.com/c36tf0vvFq
Hence, Reopening the ticket.
Thanks!

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : http://somup.com/c3XeekvgWV
Thanks!
