### ISSUE TITLE
Documentation> " State Changes" link> Clicking on link "State Changes" does not open any page

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#476]
Describe the bug
Clicking on link "State Changes" does not open any page.

To Reproduce

1. Go to https://react-magma.cengage.com/version/2.5.7/api/select/#controlled
2. Click on "State Changes" link
3. Verify that link is not navigating to any page

Expected behavior
Clicking on link "State Changes" should open the appropriate page.

Screenshots
https://somup.com/c3nXlxZR2u

Desktop:

OS: [Win 10]
Browser [chrome]
Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : http://somup.com/c36u1FvxQE
Thanks!
