### ISSUE TITLE
Documentation> "Search Props" link> Link "Search Props" is navigating to incorrect location

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#484]
Describe the bug
Link "Search Props" is navigating to heading "Change Events" instead of heading "Search Props"

To Reproduce

1.Go to https://react-magma.cengage.com/version/2.5.7/patterns/header/#search
2.Click on "Search Props" link
3. Verify that link is navigating to heading "Change Events"

Expected behavior
Link "Search Props" should navigate to correct location.

Screenshots
https://somup.com/c3n21fZWH4

Desktop (please complete the following information):
OS: [Win 10]
Browser [chrome]
Version [Chrome version: Version  98.0.4758.82 (Official Build) (64-bit)]

**Comment by greenervigil** [comment]
Will not fix

**Comment by Uditsingh67** [comment]
As per the above comment move this ticket to done .

**Comment by Uditsingh67** [comment]
As per the above comment move this ticket to done .
