### ISSUE TITLE
Documentation> "useMediaQuery hook link">  Page 'Not Found' opens if user clicks 'useMediaQuery hook' link

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#486]
Describe the bug
"Not Found" error message is appearing upon clicking the link "useMediaQuery hook".

To Reproduce

1. Go to https://react-magma.cengage.com/version/2.5.7/patterns/header/#responsive_behavior
2. Click on "useMediaQuery hook" link
3. Verify the error

Expected behavior
Link 'useMediaQuery hook 'should navigate to relevant page instead of 'Not Found'

Screenshots
https://somup.com/c3n213ZWJF

Desktop:

OS: [Win 10]
Browser [chrome]
Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=celRe
Thanks!
