### ISSUE TITLE
a11y_Container> Gutters> A11y> 2 incomplete is appearing

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#495]
**Describe the bug**
Container>> "2 incomplete" is appearing for "Gutters". 

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/container--gutters'
2. Click on 'Accessibility" add on
3. "2 incomplete" is appearing

**Expected behavior**
"0 incomplete" should appear for Container> Gutters.

**Screenshots**
https://somup.com/c3n2jlZWLH

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by ccedrone** [comment]
This appears to be an issue with the a11y Storybook plugin. No plans to fix at this time.
