### ISSUE TITLE
a11y_Indeterminate checkbox> Inverse> A11y> 1 incomplete is appearing

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#498]
**Describe the bug**
Indeterminate checkbox>> "1 incomplete" is appearing for "Inverse". 

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/indeterminate-checkbox--inverse'
2. Click on 'Accessibility" add on
3. "1 incomplete" is appearing

**Expected behavior**
"0 incomplete" should appear for Indeterminate checkbox> Inverse.

**Screenshots**
https://somup.com/c3n2jxZWN7

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
The issue is fixed.
Storybook Link : https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/indeterminate-checkbox--inverse
See Screen-cast : http://somup.com/c3jQekuJTz
Thanks!

**Comment by Uditsingh67** [comment]
Issue does not exist.
See Screen-cast : http://somup.com/c3jv12UlC3
