### ISSUE TITLE
Bug_Alert> Inverse> Control prop 'isInverse'> Preview is not getting changed upon toggling the True/False

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#534]
**Describe the bug**
Dark background is displayed even if 'isInverse' is 'False'.

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/alert--inverse'
2. Click on 'Controls'
3. Select the 'isInverse' control prop
4. Toggle it into 'True/False'
5. Verify that preview is not getting changed

**Expected behavior**
Preview should get changed upon toggling the True/False.

**Screenshots**
https://somup.com/c3no69TVMO

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by silvalaura** [comment]
I confirmed with @orion-cengage that alerts currently don’t have different colors for dark backgrounds. So turning on that prop won’t show any visible changes. This is the expected behavior. 

We will address adding the isInverse state to Alerts in RM3.
