### ISSUE TITLE
Bug_Button> Default and Inverse> Control prop 'type'> Preview is not getting changed upon selecting the 'type' options.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#536]
**Describe the bug**
 Preview is not getting changed upon selecting the 'button', 'submit', and 'reset' type options for **Default and Inverse components**.

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/button--default'
2. Click on 'Controls'
3. Select the 'type' options
4. Verify that preview is not getting changed

**Expected behavior**
Preview should get changed upon selecting the 'type' options.

**Screenshots**
https://somup.com/c3noXgTV83

**Desktop :**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by silvalaura** [comment]
I just confirmed that changing the type does update. In this case, it's just an HTML property (button type) and there are no visual changes to update:
![image](https://user-images.githubusercontent.com/91160746/162513698-7a66e16d-09c9-49c5-b7e6-8422f903659c.png)
![image](https://user-images.githubusercontent.com/91160746/162513874-4292ec30-2307-4bdb-9804-d0703f655ff0.png)
![image](https://user-images.githubusercontent.com/91160746/162513983-c6f8d2f1-4efe-4e30-949a-cedc94282824.png)

This is functioning as designed, so I will close this.
