### ISSUE TITLE
Bug_Datagrid> Colored rows> hasHoverStyles control prop> Preview is not getting changed when hover the mouse on content

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#540]
**Describe the bug**
On hovering the mouse on the content, no change appears in preview if 'hasHoverStyles' is true.

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datagrid--colored-rows'
2. Click on 'Controls'
3. Select the 'hasHoverStyles' control prop
4. Toggle it into 'True'
5. Hover the mouse on content, 

**Expected behavior**
Row should get selected when hover the mouse on content if 'hasHoverStyles' is true.

**Screenshots**
https://somup.com/c3noI0TnV9

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Additional context**
For Default> WE have observed that when hovers the mouse on content, the row appears highlighted if 'hasHoverStyles' is true.

**Comment by silvalaura** [comment]
In this example (when not all rows are colored) we can see that the `hasHoverStyles` is visible for the rows that are not colored:

https://storybook-preview-636--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datagrid--colored-rows&args=rows[1].color:!undefined;rows[2].color:!undefined;hasHoverStyles:true 

We didn't intend for the colored rows to also have hover states. This is functioning as designed, so closing as won't fix.
