### ISSUE TITLE
Bug_Datagrid> Colored rows> 'hasZebraStripes' control prop> Preview is not getting changed if hasZebraStripes is 'True'

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#541]
Describe the bug
Preview is not getting changed if hasZebraStripes is 'True'

To Reproduce

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datagrid--colored-rows'
2. Click on 'Controls'
3. Select the 'hasZebraStripes' control prop
4. Toggle it into 'True'
5. Verify the preview

Expected behavior
Preview is not getting changed if hasZebraStripes is 'True'

Screenshots
https://somup.com/c3nDh4TeDV

Desktop:

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

Additional context
For Default> We have observed that if 'hasZebraStripes' is true, the alternate row appears highlighted.

**Comment by silvalaura** [comment]
@orion-cengage What is the expectation for this as far as design/usage? Should consumers be able to have colored rows and also set hasZebraStripes to true, or are these mutually exclusive?

**Comment by silvalaura** [comment]
Both colored rows and hasZebraStripes is working as expected:
![datagrid_zebra (1)](https://user-images.githubusercontent.com/91160746/162003595-0b27ce9f-eb15-4850-8245-1abaeae78be6.gif)

The story in storybook happens to show all colored rows which override the zebra stripes, but once the color is removed, the stripes as working.
