### ISSUE TITLE
Bug_Datagrid> Pagination Changed Defaults> 'paginationProps' control prop> Error message is appearing on preview screen when manipulating the data in 'defaultRowsPerPage' and 'rowsPerPageValues'.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#542]
**Describe the bug**
Error message 'Cannot read properties of undefined (reading 'label')
' is appearing on preview screen when manipulating the data in 'defaultRowsPerPage' and 'rowsPerPageValues'.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datagrid--pagination-changed-defaults'
2. Click on 'Controls'
3. Select the 'paginationProps' control prop
4. Change the data in 'defaultRowsPerPage' and add the same values in 0 index for 'rowsPerPageValues' 
5. Verify the preview

**Expected behavior**
Error message should not appear  on preview screen when manipulating the data in 'defaultRowsPerPage' and 'rowsPerPageValues'.

**Screenshots**
https://somup.com/c3nD1lTeFi

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Additional context**
We have observed that appropriate data is appearing after refreshing the page.

**Comment by silvalaura** [comment]
Fixed indirectly
