### ISSUE TITLE
Bug_Datagrid> Controlled Pagination> 'paginationProps' control prop> Error message is appearing on preview screen when manipulating the data in 'rowsPerPageValues'.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#543]
**Describe the bug**
Error message 'Cannot read properties of undefined (reading 'label')' is appearing on preview screen when manipulating the data in 'rowsPerPageValues'.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datagrid--controlled-pagination'
2. Click on 'Controls'
3. Select the 'paginationProps' control prop
4. Change the data in 0 index for 'rowsPerPageValues' 
5. Verify the preview

**Expected behavior**
Error message is appearing on preview screen when manipulating the data in 'rowsPerPageValues'.

**Screenshots**
https://somup.com/c3nD1OTeF9

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Additional context**
1. We have observed that error message is appearing even after refreshing the page.
2. We have also observed that appropriate preview page appears if we changed the data in rowsPerPageValues : [
1 : #
2 : #

**Comment by silvalaura** [comment]
Fixed indirectly
