### ISSUE TITLE
Bug_FormFieldContainer> Default> 'isInverse' control prop> Text 'Hello test' gets disappear if 'isInverse' control prop is 'True'.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#546]
**Describe the bug**
Text 'Hello test' gets disappear if 'isInverse' control prop is 'True'.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/formfieldcontainer--default'
2. Click on 'Controls'
3. Select the 'isInverse' control prop 
4. Toggle it into 'True'
5. Verify the preview 

**Expected behavior**
Dark background should appear if 'isInverse' control prop is 'True'.

**Screenshots**
https://somup.com/c3nDi9TeTO

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Additional context**
1. As per the documentation, If 'isInverse' is true, the component will have inverse styling to better appear on a dark background. However, for 'FormFieldContainer', text gets disappears instead of showing the dark background.

**Comment by silvalaura** [comment]
Now that we've added an addon to Storybook to see a dark background, we can confirm that flipping `isInverse` to true does not make the text disappear, it's just white (and invisible against the default white background):
https://storybook-preview-636--upbeat-sinoussi-f675aa.netlify.app/?path=/story/formfieldcontainer--default&args=isInverse:true&globals=backgrounds.grid:false;backgrounds.value:!hex(333333)

The consumer using this component would be providing the dark background (if isInverse is true) to wrap this component, so I don't think it's necessary at this time for us to add that here. Closing as won't fix.
