### ISSUE TITLE
Bug_IconButton> Default/Inverse/Icon Only/Animated Icon> 'type' control prop> Preview is not getting changed upon selecting the 'type' options.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#547]
**Describe the bug**
Preview is not getting changed upon selecting the 'button', 'submit', and 'reset' type options for Default, Inverse, Icon Only and Animated Icon components.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/iconbutton--default'
2. Click on 'Controls'
3. Select the 'type' options
4. Verify that preview is not getting changed

**Expected behavior**
Preview should get changed upon selecting the 'type' options.

**Screenshots**
https://somup.com/c3nDj2TeOu

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by silvalaura** [comment]
I just confirmed that changing the type does update. In this case, it's just an HTML property (button type) and there are no visual changes to update:

![image](https://user-images.githubusercontent.com/91160746/161786872-db1f73b4-857d-4add-8cde-c5d91e302920.png)
![image](https://user-images.githubusercontent.com/91160746/161786900-e68017a1-3cc1-4eea-b4d7-1558a4806aeb.png)
![image](https://user-images.githubusercontent.com/91160746/161786928-44084a70-10a1-4e3e-8f76-c053fbcb1652.png)

This is functioning as designed, so I will close this.
