### ISSUE TITLE
Bug_Input> Inverse> 'isInverse' control prop> Text 'Example' appears faded if 'isInverse' control prop is 'False'. 

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#553]
**Describe the bug**
Text 'Example' appears faded if 'isInverse' control prop is 'False'. 

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/input--inverse'
2. Click on 'Controls'
3. Select 'isInverse' control prop 
4. Toggle 'isInverse' to 'false'
5. Verify the preview

**Expected behavior**
Dark background should disappear if 'isInverse' control prop is 'False'.

**Screenshots**
https://somup.com/c3nD6uTea5

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

Additional context

As per the documentation, If 'isInverse' is true, the component will have inverse styling to better appear on a dark background. However, for 'Input>Inverse', text gets faded instead of disappearing the dark background.

**Comment by silvalaura** [comment]
The Input component is working as expected and isInverse has the correct behavior. In Storybook, the team has chosen to add a background for Inverse to make it clearer when the isInverse toggled is switched, but we do not expect that background color to also be toggled as it is not part of the component.

Closing this bug as "wontfix".
