### ISSUE TITLE
Bug_NativeSelect> Default/Disabled/Has Error/Helper Message> 'isInverse' control prop> Text 'Select' and the boundary of the box gets disappear if 'isInverse' control prop is 'True'.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#554]
**Describe the bug**
Text 'Select' and the boundary of the box gets disappear if 'isInverse' control prop is 'True' for Default, Disabled, Has Error, Helper Message.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/nativeselect--default'
2. Click on 'Controls'
3. Select 'isInverse' control prop 
4. Toggle it into 'true'
5. Verify the preview

**Expected behavior**
Dark background should appear if 'isInverse' control prop is 'True'.

**Screenshots**
https://somup.com/c3nD6gTezz

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

Additional context

As per the documentation, If 'isInverse' is true, the component will have inverse styling to better appear on a dark background. However, for 'NativeSelect', text and the boundary of the box get faded instead of showing the dark background.

**Comment by silvalaura** [comment]
Now that we've added an addon to Storybook to see a dark background, we can confirm that flipping isInverse to true does not make the text disappear, it's just white (and invisible against the default white background): https://storybook-preview-636--upbeat-sinoussi-f675aa.netlify.app/?path=/story/nativeselect--default&args=isInverse:true&globals=backgrounds.value:!hex(333333)

The consumer using this component would be providing the dark background (if isInverse is true) to wrap this component, so I don't think it's necessary at this time for us to add that here. Closing as won't fix.
