### ISSUE TITLE
Bug_PasswordInput> Inverse> 'isInverse' control prop> Text 'Password' appears faded if 'isInverse' control prop is 'False'.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#556]
**Describe the bug**
Text 'Password' appears faded if 'isInverse' control prop is 'False'.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/passwordinput--inverse'
2. Click on 'Controls'
3. Select 'isInverse' control prop 
4. Toggle it into 'false'
5. Verify the preview

**Expected behavior**
Dark background should disappear if 'isInverse' control prop is 'False'.

**Screenshots**
https://somup.com/c3nDX0TegP

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

Additional context

As per the documentation, If 'isInverse' is true, the component will have inverse styling to better appear on a dark background. However, for 'PasswordInput>Inverse, text gets faded instead of disappearing the dark background.

**Comment by silvalaura** [comment]
It looks like this is how we approach the `isInverse` stories for all components: the background color is hardcoded and so is the value of `isInverse`. The goal of the story is to prove the component's `isInverse` works, and not necessarily the decorator's. 

@orion-cengage @ccedrone thoughts on whether this needs to be addressed or if it can be closed as no plans to fix?

**Comment by ccedrone** [comment]
This isn't a bug to me as the logic is working properly.

**Comment by silvalaura** [comment]
The PasswordInput component is working as expected and isInverse has the correct behavior. In Storybook, the team has chosen to add a background for Inverse to make it clearer when the isInverse toggled is switched, but we do not expect that background color to also be toggled as it is not part of the component.

Closing this bug as "wontfix".
