### ISSUE TITLE
Bug_Tag> On Delete With Icon> 'color' control prop> Preview is not getting changed upon selecting the 'color' control.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#567]
**Describe the bug**
Preview is not getting changed upon selecting the 'color' control.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tag--on-delete-with-icon'
2. Click on 'Controls'
3. Select 'color' control prop
4. Change the colors
5. Verify the preview

**Expected behavior**
Preview should get changed upon selecting the 'color' control.

**Screenshots**
https://somup.com/c3nbjkThlf

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=MVp6d
Hence, Closing the ticket.
Thanks!
