### ISSUE TITLE
Bug_Tag> All components> 'isInverse' control prop> Background of the button gets changed instead of appearing the dark blue background for the components.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#576]
**Describe the bug**
Background of the button gets changed instead of appearing the dark blue background for the following components:
- Default
- With Icon
- Size
- Size With Icon
- Size With Delete
- Size With Icon Delete
- On Click
- On Delete
- On Delete With Icon
- Primary
- Low Contrast
- High Contrast
- Inverse

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tag--default&args=isInverse:true'
2. Select 'isInverse' control prop
3. Toggle it into 'True'
4. Verify the preview

**Expected behavior**
Dark blue background should appear instead of changing the background of the button.

**Screenshots**
https://somup.com/c3nbXrThTx

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Additional context**
As per the other inverse component, For example: Dropzone> Default> isInverse> Blue background appears if 'isInverse' control prop is 'True.

**Comment by rcgillet** [comment]
Working as intended. `isInverse` is a prop to change the background color of the `Tag`. Not to change the entire background. These are components, not entire applications, so the props change the individual components look.
