### ISSUE TITLE
Bug_Patterns> Default/ Call to Action/ Search/ Custom Children/Icons Buttons As Children/ Everything/ Everything Inverse> 'logo' control prop> Error message appears if user click the 'ref' value and clicks outside without changing the value.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#578]
**Describe the bug**
Error message appears if user clicks the 'ref' value and clicks outside without changing the value.

**To Reproduce**
1. Go to https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/patterns-header--default&args=logo.key:Test;logo.ref:null
2. Click on 'Controls'
3. Select 'logo' control prop
4. Click on 'ref' value
5. Verify the Preview

**Expected behavior**
Error message should not appear.

**Screenshots**
https://somup.com/c3nblFThUL

**Desktop:**
OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by rcgillet** [comment]
Changing an elements internal props will give an error. You would have to change the element itself in the code. This is not something we will fix as this is known to the developers and storybook is only used for development purposes.
