### ISSUE TITLE
Bug_Patterns>Logo/ Custom Children> 'logo' control prop> Error message appears if user just clicks 'key', 'ref' and 'owner' value and click out side.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#579]
**Describe the bug**
Error message appears if user click the 'key', 'ref' and 'owner' ' value and click outside without changing the value.

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/patterns-header--logo'
2. Click on 'Controls'
3. Select 'logo' control prop
4. Click on 'key'/ 'ref' / 'owner' value
5. Verify the Preview

**Expected behavior**
Error message should not appear.

**Screencast**
https://somup.com/c3nblYThv1

**Desktop:**
OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by rcgillet** [comment]
Changing an elements internal props will give an error. You would have to change the element itself in the code. This is not something we will fix as this is known to the developers and storybook is only used for development purposes.
