### ISSUE TITLE
Bug_Flex> Default/ Auto Width/ One Set Width> 'justify' control prop> Nothing happens in Preview if user change 'justify' value.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#583]
**Describe the bug**
Nothing happens in Preview if user changes 'justify' value.

**To Reproduce**
1. Go to https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/flex--default
2. Click on 'Controls'
3. Navigate to 'justify' controls
4. Change the value
5. Verify the Preview

**Expected behavior**
Preview should get changed if user changes the 'justify' value.

**Screencast**
https://somup.com/c3nblHThxf

**Desktop:**
OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by rcgillet** [comment]
See other issue for closing reason.

https://github.com/cengage/react-magma/issues/584#issuecomment-1043106438
