### ISSUE TITLE
Bug_Flex> Fixed Width/ Auto Width/ One Set Width/ Container Only/ Other Props> 'wrap' control prop> Nothing happens in Preview if user change 'wrap' value.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#584]
**Describe the bug**
Nothing happens in Preview if user changes 'wrap' value.

**To Reproduce**
1. Go to https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/flex--fixed-width
2. Click on 'Controls'
3. Navigate to 'wrap' controls
4. Change the value
5. Verify the Preview

**Expected behavior**
Preview should get changed if user changes the' wrap' value.

**Screencast**
https://somup.com/c3nblKThx2

**Desktop:**
OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by rcgillet** [comment]
![image](https://user-images.githubusercontent.com/1943204/154518513-193c9168-b453-4ea1-990c-ef4b46be806d.png)

Looking at the `element` in the console you can see that the property is being updated. `flex` is a css property to create a grid of elements essentially. There are multiple pieces that would need to be changed to see changes, including changing all of the children elements flex values as well.
