### ISSUE TITLE
Bug_Form> Default/ Expanded> 'Children' control prop> Error message appears if user click the 'ref' value and click outside without changing the value.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#586]
**Describe the bug**
Error message appears if user click the 'ref' value and click outside without changing the value

**To Reproduce**
1. Go to https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/form--default
2. Click on 'Controls'
3. Navigate to 'Children' controls
4. Click on 'ref' value
5. Verify the Preview

**Expected behavior**
Error message should not appear.

**Screencast**
https://somup.com/c3nblPThxK

**Desktop:**
OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by rcgillet** [comment]
`refs` are references to another element. By updating the `ref` prop with no other element it errors out because there is nothing to reference. This is not a prop you can just change on the fly without having the `element` available to put in as a value.
