### ISSUE TITLE
Bug_Pagination> Default Selected/ Adjacent Pages/ Edge Pages> 'defaultPage'' control prop> Default page does not change in Navigation bar of Preview if user change 'defaultPage' value.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#588]
**Describe the bug**
1. Default page does not change in Navigation bar of Preview if user change 'defaultPage' value
2. Also, observed that if user reloads the page after changing the value, Navigation bar in Preview window reflects the change but 'defaultPage' value in controls is still same i.e. 2.

**To Reproduce**
1. Go to https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/pagination--default
2. Click on 'Controls'
3. Navigate to 'defaultPage' controls
4. Change the value
5. Verify the Preview
6. Reload the browser page
7. Verify that previously changed value is selected in navigation bar of Preview but controls reflects the default valye i.e. 2

**Expected behavior**
1. Default page should change in Navigation bar of Preview if user changes 'defaultPage' value.
OR
2. If user reloads the page after changing the value, 'defaultPage' value in controls should appear same as the value appears in navigation bar.

**Screencast**
https://somup.com/c3nbIiThyw

**Desktop:**
OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by rcgillet** [comment]
Changing `defaultPage` in `storybook` will not cause a full re-render, which is how that prop gets propagated. I tested it on our `codesandbox` that is linked in the docs and the `defaultPage` is being used on initial render as expected.
