### ISSUE TITLE
RM3 / Branding refresh / Slider / Light background

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#594]
**Purpose:** Update the styling of Slider for the new branding.

**inVision:** https://cengage.invisionapp.com/share/M912EDCFJ6PU

#### Prerequisites:
- Color palette in place
- Typography updated
- Progress Bars updated
- Work Sans available

![image](https://user-images.githubusercontent.com/24397282/155778815-61b9f72d-9b3b-44e2-81b1-b45f51a1e6f6.png)

## AC

- If still necessary, change font from Open Sans to Work Sans

### 1.0 Track

![image](https://user-images.githubusercontent.com/24397282/155784299-bc5f74a1-685c-4c5a-8662-6d6be5e9f48e.png)

- 1.1 Background: neutral-100
- 1.2 Border: 1px solid neutral-500
- 1.3 Height: 8px

### 2.0 Handle

![image](https://user-images.githubusercontent.com/24397282/155799274-48397d9e-b483-47bf-8a1f-d580fa36808c.png)

- 2.1 Background: neutral-100
- 2.2 Border: 1px solid neutral-500
- 2.3 No drop shadow

### 3.0 Filled portion of track

![image](https://user-images.githubusercontent.com/24397282/155800228-2c2a3823-ee2e-446b-8ca5-f78fa6296aa4.png)

- 3.1 Background: primary-500

**Comment by silvalaura** [comment]
Closing as these styles have been applied to the WIP PR (#360), and the issue will be completed as part of #64
