### ISSUE TITLE
RM3 / Branding refresh / Slider / Dark background

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#597]
**Purpose:** Update the styling of Slider for the new branding.

**inVision:** https://cengage.invisionapp.com/share/M912EDCFJ6PU

#### Prerequisites:
- Color palette in place
- Typography updated
- Progress Bars updated
- Work Sans available

![image](https://user-images.githubusercontent.com/24397282/155801003-a2bf8f79-d0c2-4ddd-9e2b-538e84c41ae2.png)

## AC

- If still necessary, change font from Open Sans to Work Sans

### 1.0 Track

![image](https://user-images.githubusercontent.com/24397282/155801060-bce77c2e-f23e-470a-b1f1-1e705c619e92.png)

- 1.1 Background: neutral-900, opacity 0.25
- 1.2 Border: 1px solid neutral-100, opacity 0.50
- 1.3 Height: 8px

### 2.0 Handle

![image](https://user-images.githubusercontent.com/24397282/155801269-b3d38bce-9524-4dcb-a79b-94228e719177.png)

- 2.1 Background: neutral-100
- 2.2 No border
- 2.3 No drop shadow

### 3.0 Filled portion of track

![image](https://user-images.githubusercontent.com/24397282/155801325-13a3b990-7e2b-4993-8284-8057c3812eed.png)

- 3.1 Background: tertiary-500

**Comment by silvalaura** [comment]
Closing as these styles have been applied to the WIP PR (#360), and the issue will be completed as part of #64
