### ISSUE TITLE
Patterns - Header: Module not found error

### ISSUE THREAD

**Issue by ccedrone** [cengage/react-magma#609]
Proper configuration by [documentation](https://react-magma.cengage.com/version/2.5.8/patterns/header/) results in an error: Module not found: Error: Can't resolve '@cengage-patterns/header'

Reported by Tom Nagy with following package.json:

"dependencies": {
    "@emotion/core": "^10.3.1",
    "@emotion/styled": "^10.0.27",
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "date-fns": "^2.16.0",
    "downshift": "^5.4.7",
    "framer-motion": "^4.1.17",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-magma-dom": "^2.5.8",
    "react-magma-icons": "^2.3.3",
    "react-scripts": "5.0.0",
    "uuid": "^8.3.0",
    "web-vitals": "^2.1.4"
  
<img width="1920" alt="Error" src="https://user-images.githubusercontent.com/77400920/159775604-76a4c4f8-53ea-4492-80b1-f570f7c1a95e.png">
}

**Comment by silvalaura** [comment]
Mmm, we may need more information about this. Did they install `"@cengage-patterns/header": "2.0.10",` in their dependencies? It's important to know that Patterns have their own package and are not part of the `react-magma-dom` package.

I think the documentation is accurate as it works on the CodeSandbox (https://codesandbox.io/s/jhbs86?module=/example.tsx&file=/example.tsx).

**Comment by tomnagy** [comment]
After installing "@cengage-patterns/header" I was able to try the header pattern. 

I think it would be helpful to other users if there was an explicit line that says some like 
"To try this, Install: `npm i @cengage-patterns/header --save`

**Comment by silvalaura** [comment]
@tomnagy Great point. This should be listed under Setup Requirements. We can do that, thanks for the feedback.
