### ISSUE TITLE
Dropdowns Update: Viewport detection/positioning

### ISSUE THREAD

**Issue by joasmi723** [cengage/react-magma#62]
**Description**
Allow dropdowns to reposition intelligently based on viewport/window.

If there isn't enough room for the dropdown menu to display in the position it's supposed to, then it will automatically move to the opposite position. Example: down position will move to the up position when there isn't enough space below the button.

We want to use https://floating-ui.com/.

The current prop `dropDirection` in Dropdown should be the default, and only if it doesn't fit in that position should we change the direction.

Here's a list of the components that need this functionality added to them. Depending on the level of effort to implement floating ui, we can make these separate tickets:
- Combobox
- Date picker
- Dropdown
- Select

**Note**
Popper is implemented on the Tooltip component, but Popper is now deprecated. We will update Tooltip at a later time and that is out of scope for this ticket.

**Comment by silvalaura** [comment]
Reference: 

PR with Floating UI
https://stash.cengage.com/projects/TRUST/repos/fx-ui/pull-requests/1537/diff#src%2Fcomponents%2Froutes%2FSearch%2Fcomponents%2FFilterDropdown.tsx

**Comment by silvalaura** [comment]
Confirmed the changes behave as expected for:
- Dropdown ✅ 
- Combobox ✅
- Select ✅
- DatePicker ✅
