### ISSUE TITLE
Bug_Tag>On Delete With Icon>Page goes blank when user select 'LowContrast' Color  Control.

### ISSUE THREAD

**Issue by Uditsingh67** [cengage/react-magma#641]
To Reproduce

Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tag--on-delete-with-icon&args=color:lowContrast'
Click on 'Controls'
Select 'color' control prop
Change the colors
Verify the preview

Expected behavior
Preview should get changed upon selecting the 'color' control.

Screenshots
https://www.screenpresso.com/=MacXb

Desktop:
OS: [Win 10]
Browser [chrome]
Version 100.0.4896.75 (Official Build) (64-bit)

**Comment by silvalaura** [comment]
With our latest release of storybook, we have the ability to change the background color. Here we can see that `lowContrast` appears blank on a light background, but is visible with a dark background:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/91160746/163017516-772f4799-9974-49ac-92a2-fa38f19fc36f.png">

https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tag--on-delete-with-icon&args=color:lowContrast&globals=backgrounds.value:!hex(333333)

I think this is functioning as designed, so closing as "won't fix"
