### ISSUE TITLE
RM3 / Color system

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#648]
Purpose: Create color system and naming convention that not only allows us to apply our brand, but also provide a scalable system  for use by other brands.

inVision: https://cengage.invisionapp.com/share/R312LU2EX4GN

### AC

1.0 Allow groupings of color, each based on a base color or starting point.  Each group can then consist of up to 9 shades and tints including that base color.  The base color takes the 500-position.
- 1.1 Define the following groups:
  - 1.1.1 Primary
  - 1.1.2 Secondary
  - 1.1.3 Tertiary
  - 1.1.4 Neutral
  - 1.1.5 Info
  - 1.1.6 Danger
  - 1.1.7 Warning
  - 1.1.8 Success

2.0 For our use of the groups, define the following colors within each group for the new Higher Ed branding
- 2.1 Primary
  - 2.1.1 primary100 - #E8E9F8
  - 2.1.2 primary200 - #BABDE9
  - 2.1.3 primary300 - #8B91DA
  - 2.1.4 primary400 - #5D65CB
  - 2.1.5 primary500 - #3942B0
  - 2.1.6 primary600 - #292F7C
  - 2.1.7 primary700 - #1A1E51
- 2.2 Secondary
  - 2.2.1 secondary500 - #FEE449
  - 2.2.2 secondary600 - #FEDA0D
  - 2.2.3 secondary700 - #ECC901
- 2.3 Tertiary
  - 2.3.1 tertiary500 - #CDDEFF
  - 2.3.2 tertiary600 - #A2C1FF
  - 2.3.3 tertiary700 - #79A5FF
- 2.4 Neutral
  - 2.4.1 neutral100 - #FFFFFF
  - 2.4.2 neutral200 - #F5F5F5
  - 2.4.3 neutral300 - #D4D4D4
  - 2.4.4 neutral400 - #8D8D8D
  - 2.4.5 neutral500 - #707070
  - 2.4.6 neutral600 - #5A5A5A
  - 2.4.7 neutral700 - #454545
  - 2.4.8 neutral800 - #2D2D2D
  - 2.4.9 neutral900 - #000000
- 2.5 Info
  - 2.5.1 info100 - #E8F5FC
  - 2.5.2 info200 - #A6DEFF
  - 2.5.3 info300 - #2FB3FF
  - 2.5.4 info400 - #009AF3
  - 2.5.5 info500 - #0074B7
  - 2.5.6 info600 - #005F96
  - 2.5.7 info700 - #004A75
- 2.6 Danger
  - 2.6.1 danger100 - #FCEBEA
  - 2.6.2 danger200 - #FAAEB0
  - 2.6.3 danger300 - #E8716D
  - 2.6.4 danger400 - #E24943
  - 2.6.5 danger500 - #D32821
  - 2.6.6 danger600 - #A91F1A
  - 2.6.7 danger700 - #7F1714
- 2.7 Warning
  - 2.7.1 warning100 - #FCEEE5
  - 2.7.2 warning200 - #F6CDB2
  - 2.7.3 warning300 - #E98B4C
  - 2.7.4 warning400 - #E06A1C
  - 2.7.5 warning500 - #AD5115
  - 2.7.6 warning600 - #8D4311
  - 2.7.7 warning700 - #6E340E
- 2.8 Success
  - 2.8.1 success100 - #E3FAEA
  - 2.8.2 success200 - #ACF0C1
  - 2.8.3 success300 - #3EDD6E
  - 2.8.4 success400 - #21B94E
  - 2.8.5 success500 - #178037
  - 2.8.6 success600 - #136A2D
  - 2.8.7 success700 - #0F5323

**Comment by silvalaura** [comment]
@orion-cengage Any updates to the `iterable colors`?
```
  iterableColors: [
    '#0085CC',
    '#E0004D',
    '#FA6600',
    '#48A200',
    '#B12FAD',
    '#00A393',
    '#00507A',
    '#8F0033',
    '#B84900',
    '#255200',
    '#711E6E',
    '#005249',
  ],
```

These are currently used in GraphTooltip and LineChart.

**Comment by orion-cengage** [comment]
Ah, those are for the data viz charts.  No changes at this time.  We still need them but I haven't looked yet to see if any of them need to be changed.  Perhaps we can handle those potential changes in a separate issue?
