### ISSUE TITLE
Update the node version in the workflows to LTS

### ISSUE THREAD

**Issue by greenervigil** [cengage/react-magma#689]
**Describe the bug**
Currently the node version the workflows is set to 14 but LTS is 16.

We should update to the most recent version or provide a range of versions.

**Comment by silvalaura** [comment]
Request: https://cengage.slack.com/archives/C8Y4FR63U/p1661434849921109 & https://cengage.slack.com/archives/C8Y4FR63U/p1661435858867199

We need to do this for `react-magma-dom` and `react-magma-icons`. 

Can we do the React version at the same time?
