### ISSUE TITLE
react-magma-docs: New Home Page follow up updates

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#699]
In https://github.com/cengage/react-magma/issues/318, we updated the home page. This issue is to fix some outstanding items in order to fully match the design: https://cengage.invisionapp.com/share/Z3RH81FTNMC

**Acceptance Criteria:**
- Responsive behavior (see prototype)
-- 768px wide and below, the Designing and Developing sections stack
- Start Contributing button should have the Github Icon

**Comment by Uditsingh67** [comment]
We verified this ticket.
Acceptance Criteria:

Responsive behavior (see prototype)
-- 768px wide and below, the Designing and Developing sections stack
Start Contributing button should have the Github Icon : PASS

See Screen-cast : http://somup.com/c3QjhvUZpY
