### ISSUE TITLE
Docs: Ensure components List - SchemaRenderer have all props documented

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#706]
### Describe the bug
There are missing props in the docs for a lot of components. This issue is to review every component from **List** through **SchemaRenderer**, and ensure all props are properly documented in the props table.

![image](https://user-images.githubusercontent.com/91160746/169891508-e2aa9c8e-6892-4ad2-ac39-09de1e5e32f8.png)

### Example: TimePicker
**To Reproduce**
1. Go to https://next--upbeat-sinoussi-f675aa.netlify.app/api/time-picker/

**Expected behavior**
All props are appropriately documented

**Screenshots**
![image](https://user-images.githubusercontent.com/91160746/168891692-67db0d16-e678-409b-9a15-950aace85a18.png)
vs
```
    const {
      containerStyle,
      errorMessage,
      helperMessage,
      inputStyle,
      labelStyle,
      labelText,
      minutesStep,
      onChange,
      ...other
    } = props;
```

**Comment by ccedrone** [comment]
All props have been verified as showing up appropriately except for the following components:

Breakpoints Container
Container
Dropzone
Header
Line Chart
List
