### ISSUE TITLE
RM3 / Date picker / Dark background

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#716]
**Purpose:** Update date picker with new brand styles for dark backgrounds.  Does not exist today.

![image](https://user-images.githubusercontent.com/24397282/168902351-309bc77d-b345-4658-97c2-12f840fe1cb9.png)

## AC

1.0 All buttons within the calendar component use inverse primary link variant.
2.0 Color for all the normal text and numbers is netural-100
3.0 Current day indicator (triangle) is secondary-500
4.0 Border around each day in the calendar is primary-200 
5.0 Container for the dropdown is same as dropdown component - primary-500 background with border.

**Comment by silvalaura** [comment]
@orion-cengage can I get colors for this screen, please?
<img width="307" alt="image" src="https://user-images.githubusercontent.com/91160746/169140447-90c78aa9-f84e-47ce-9e0a-337e9e99402c.png">

**Comment by orion-cengage** [comment]
@silvalaura Here you go!

![image](https://user-images.githubusercontent.com/24397282/169146437-2967d39d-e954-4d4f-ba5d-ef1b7cde6526.png)
