### ISSUE TITLE
i18n: when setting the date in dd/MM/yyyy format, date gets changed

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#748]
**Describe the bug**
We’ve run into an issue with this internationalisation. When using dd/MM/yyyy and setting 8th June and deselecting the dropdown, it ends up setting the value to 6th August (swapping month and date values).
If a value is selected that is valid dd/MM/yyyy but not MM/dd/yyyy (e.g. 13/10/2022) it loses the value entirely from the datepicker.

Add to the default formatting ('MMMM d, yyyy')

**To Reproduce**
1. Go to https://codesandbox.io/s/react-magma-example-forked-wk2fqb
2. Click on June 8th
4. Notice date changed to August 6th

**Expected behavior**
Date does not change

**Notes**
This happens any time the input value is invalid

**Comment by Uditsingh67** [comment]
The issue is fixed.
**See Screen-cast:** http://somup.com/c3jQQRuJKe
Thanks!

**Comment by Uditsingh67** [comment]
Issue does not exist.
See Screen-cast: http://somup.com/c3jwiTU2Tx
