### ISSUE TITLE
What is the functionality of Combo box in Component SchemaRenderer - Form

### ISSUE THREAD

**Issue by hkrishna29** [cengage/react-magma#766]
**Describe the bug**
What is expected behavior of  "Combo box"

**To Reproduce**
1. Go to https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/schemarenderer--form
2. Click on component 'Form'
3. In field Combo box , enter data not available  in the dropdown and click enter , the option are added to the list  

**Expected behavior**
Do not know .

**Additional context**
![2022-06-10_11h31_43](https://user-images.githubusercontent.com/90398760/173100848-9ff1eb5b-fefe-40ee-8f95-b5a75290a68a.png)

 Tested in storybook

**Comment by silvalaura** [comment]
It looks like Multi is behaving as expected, but there's a bug with default.
