### ISSUE TITLE
Add link to github in the docs.

### ISSUE THREAD

**Issue by aaronmaturen** [cengage/react-magma#77]
Right now we don't have anything in the docs pointing at github ... probably should add that, either has a general github icon or a link in all the API sections to their corresponding components

**Comment by joasmi723** [comment]
I like the idea of having both -- a general github icon in the header, as well as a link on all of the sections of the API to their respective components.  

If/when we add it to the header, we also still need to add something that indicates the version we are on.    I know we have mock-ups for introducing a dropdown for changing versions:  

![version-dropdown](https://user-images.githubusercontent.com/18616182/104377404-14a05900-54ec-11eb-95f6-0e8242600855.png)

**Comment by joasmi723** [comment]
I talked with Orion.  He recommended adding the link to Github in the left navigation, underneath the `Introduction` link, above the `Develop` and `Design` accordions.  The link should open in a new window, and include the `ExternalLinkIcon` icon.  It should be the same font size/weight as the `Introduction` link.
