### ISSUE TITLE
Bug: Select > Placeholder: Wrong color

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#770]
**Describe the bug**
The color of the placeholder text in Selects matches the color of a selected option

**To Reproduce**
1. Go to https://next--upbeat-sinoussi-f675aa.netlify.app/api/select/#placeholder
2. Click on an option
3. Notice that the color of the placeholder matches the color of a selected option

**Expected behavior**
The Placeholder in selects are a lighter color
- not inverse: neutral500
- isInverse: transparentize(0.3, magma.colors.neutral100)

**Screenshots**
![image](https://user-images.githubusercontent.com/91160746/173103815-a5e1a263-7fba-4d46-b54e-b97d99ba9f84.png)

**Comment by orion-cengage** [comment]
I tested on both Storybook and the Docs, and all looks good.
