### ISSUE TITLE
RM3 Buttons - New state colors

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#789]
Purpose: Update the hover/focus/active states on buttons using colors from the new color palette.  This means removing the tech that automatically tints/shades the buttons.

inVision (2 screens): https://cengage.invisionapp.com/console/share/FAVJYPH2XGU

#### Primary
![image](https://user-images.githubusercontent.com/24397282/175314969-fa85b369-13ed-4621-9dd1-bab03bde50a8.png)

- Hover + focus background = primary600
- Active background = primary700

#### Secondary
![image](https://user-images.githubusercontent.com/24397282/175315012-c88418f7-865c-4215-b725-d424d7c21da7.png)

- Hover + focus background = primary100
- Active background = primary200
- Active text/icon color = primary600

#### Marketing
![image](https://user-images.githubusercontent.com/24397282/175315068-f24d3e79-340f-4b32-bf74-6581f4dcabd9.png)

- Hover + focus background = secondary600
- Active background = secondary700
- Active text/icon color = primary600

#### Danger
![image](https://user-images.githubusercontent.com/24397282/175315119-b38d295a-274a-4c26-9274-f458eec050d2.png)

- Hover + focus background = danger600
- Active background = danger700

#### Primary
![image](https://user-images.githubusercontent.com/24397282/175315158-37442b4f-98b7-42b1-90db-48edb5d806a3.png)

- Hover + focus background = primary100
- Active background = primary200
- Active text/icon color = primary600

#### Danger
![image](https://user-images.githubusercontent.com/24397282/175315206-ea7b8c33-f0ee-433c-9a98-4164b089ab94.png)

- Hover + focus background = danger100
- Hover text/icon color = danger600
- Active background = danger200
- Active text/icon color = danger700

#### Primary
![image](https://user-images.githubusercontent.com/24397282/175315367-6bd5bd8e-74a7-4ee4-a328-6ec6e3b8df37.png)

- Hover + focus background = tertiary600
- Active background = tertiary700

#### Secondary
![image](https://user-images.githubusercontent.com/24397282/175315433-adefbcf4-271a-4506-b498-5e5c54410098.png)

- Hover + focus background = neutral900, opacity 30%
- Active background = neutral900, opacity 50%

#### Marketing
Same as above

#### Danger
Same as above

#### Primary
![image](https://user-images.githubusercontent.com/24397282/175315619-48828713-c4a3-4801-bc03-322c4f686668.png)

- Hover + focus background = neutral900, opacity 30%
- Active background = neutral900, opacity 50%

#### Danger
![image](https://user-images.githubusercontent.com/24397282/175315671-717fc96d-0ccb-4c1e-859b-f42c52d487fb.png)

- Hover + focus background = neutral900, opacity 30%
- Active background = neutral900, opacity 50%

**Comment by silvalaura** [comment]
@orion-cengage We also use darken for Badge. Should we update that as well?

**Comment by orion-cengage** [comment]
@silvalaura The badges are so small, it's nearly impossible to even see the color change.  Let's actually just remove the styling on hover/active for badges.  They can still be clicked, and you'll get the focus outline.

**Comment by silvalaura** [comment]
@ccedrone I will remove the badge styles as part of https://github.com/cengage/react-magma/issues/796 so this issue can focus on buttons
