### ISSUE TITLE
Fix focus state management on dropdown + modal

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#800]
Perkins CENG_2486, CENG_2491

These are similar and probably related issues between the dropdown and modal components.

**Dropdown**
When making a selection from the dropdown (or pressing the Escape key to close it), focus returns to the dropdown button but there is not a visible focus.

**Modal**
When closing the modal visible focus is not evident on the button that triggers the modal.

**Comment by Uditsingh67** [comment]
The Issue is Fixed.
RM Link : https://next--upbeat-sinoussi-f675aa.netlify.app/api/dropdown/
See Screen-cast : http://somup.com/c3iFfDuYYB
Thanks!
