### ISSUE TITLE
ButtonGroup should support Dropdowns

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#811]
ButtonGroup component needs to be able to add the correct spacing for Dropdowns

**Comment by Uditsingh67** [comment]
Verified on RM and Storybook as well.
**See Screen-cast :** http://somup.com/c3iF1XuYt4
**URLs:**

> RM : https://next--upbeat-sinoussi-f675aa.netlify.app/api/button-group/
> Storybook: https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/buttongroup--with-dropdowns

Thanks!
