### ISSUE TITLE
DataGrid: allow tables to be sortable by the selected items

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#828]
Currently, if you try to add the ability to sort selected items on a table, both the TableHeaderCell `onSort` function and the IndeterminateCheckbox `onChange` function gets called.

Instead, we should add a new prop to Tables (internal, to be used by DataGrid) to allow only selectable tables to also be sorted by the selected items.

**Comment by silvalaura** [comment]
QA Note: Test here: https://react-magma.cengage.com/version/2.6.0/api/datagrid/#selectable_and_sortable

**Comment by Uditsingh67** [comment]
The issue is **fixed**.
See Screen-cast : http://somup.com/c3jnhlugAO
Thanks!

**Comment by Uditsingh67** [comment]
Issue does not exist.
See Screen-cast : http://somup.com/c3jwhzU2qh
