### ISSUE TITLE
Bug_NativeSelect > Default /Has Error /Helper Message /Inverse /Has Error Inverse /Helper Message Inverse > User is not able to launch the dropdown menu by clicking on dropdown icon.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#830]
**Describe the bug:**
Dropdown menu is not launching when user clicks the dropdown icon.

**To Reproduce:**
1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/iframe.html?id=nativeselect--inverse&args=&viewMode=story'
2. Click on dropdown icon.
3. Verify that dropdown menu is not launching.

**Expected behavior:**
Dropdown menu should launch when user clicks the dropdown icon.

**Screenrecording:**
https://somup.com/c3iqI6u3kH

**Desktop:**
OS: [Win 10],Browser [chrome][Version 98.0.4758.82 (Official Build) (64-bit)]
OS: [Mac 12], Browser [Safari][Version 15.2]
OS: [iOS Device],Browser [Safari][Version 15.5]

**Comment by Uditsingh67** [comment]
The Issue is fixed.
See Screen-cast : http://somup.com/c3jffMuC5f
Thanks!

**Comment by Uditsingh67** [comment]
Issue does not exist.
See Screen-cast : http://somup.com/c3jvjVUlKl
