### ISSUE TITLE
Bug_NativeSelect > Inverse /Has Error Inverse /Helper Message Inverse > Dropdown options are not visible until the user hovers the mouse on it.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#831]
**Describe the bug:**
Dropdown options are not visible as the options are appearing in white colour.

**To Reproduce:**
1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/iframe.html?id=nativeselect--inverse&args=&viewMode=story'
2. Launch the dropdown menu.
3. Observe that dropdown options are not visible until the user hovers the mouse on it.

**Expected behavior:**
Dropdown options should appear appropriately.

**Screenrecording:**
https://somup.com/c3iqIqu3po

**Desktop:**
OS: [Win 10],Browser [chrome][Version 98.0.4758.82 (Official Build) (64-bit)]
OS: [Mac 12], Browser [Safari][Version 15.2]

**Comment by Uditsingh67** [comment]
The issue is fixed.
See screen-cast : http://somup.com/c3iYf8u0kQ
Thanks!

**Comment by silvalaura** [comment]
@Uditsingh67 The issue was with `NativeSelect` and not `Select`. Do you mind re-verifying this? https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/nativeselect--inverse

**Comment by Uditsingh67** [comment]
The issue is fixed.
See screen-cast : http://somup.com/c3irfauT6M
Thanks!
