### ISSUE TITLE
Bug_Tabs > Default/Inverse> "Disabled" cursor is not appearing when hovers on "Disabled" tab as compared to other Disabled components.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#836]
**Describe the bug:**
"Disabled" icon is not appearing when hovers on "Disabled" tab as compared to other Disabled components.

**To Reproduce:**

1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/iframe.html?id=tabs--inverse&args=&viewMode=story'
2. Hover the mouse on "Disabled" tab
3. Verify that "Disabled" icon is not appearing.

**Expected behavior:**
"Disabled" icon should appear when hovers on "Disabled" tab as compared to other Disabled components.

**Screenrecording:**
https://somup.com/c3iYiiu0Jm

**Desktop:**
OS: [Win 10],Browser [chrome][Version 98.0.4758.82 (Official Build) (64-bit)]
OS: [Mac 12], Browser [Safari][Version 15.2]

**Comment by Uditsingh67** [comment]
The Issue is fixed.
See Screen-cast : http://somup.com/c3XXhLv75r
Thanks!
