### ISSUE TITLE
react-magma-docs: Replace sidebar accordion with our own component

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#870]
Replaced the Magma site sidebar accordion component with our own.

Previous accordion: https://react-magma.cengage.com/version/3.1.1/

Our accordion: https://next--upbeat-sinoussi-f675aa.netlify.app/

**Comment by Uditsingh67** [comment]
We Verified this ticket.
See Screen-cast : http://somup.com/c3QIhDUvp2
Thanks!
