### ISSUE TITLE
a11y_Form> expanded> A11y> 1 incomplete is appearing

### ISSUE THREAD

**Issue by Uditsingh67** [cengage/react-magma#879]
**Describe the bug**
Form>> "1 incomplete" is appearing for "expanded".

**To Reproduce**
**Steps to reproduce the behavior:**

1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/form--expanded
2. Click on 'Accessibility" add on
3. "1 incomplete" is appearing

**Expected behavior**
"0 incomplete" should appear for Form> expanded.

**QA Note: 1 Violation & 1 Incomplete is displayed on iPad.**

<html>
<body>

OS | Version | Result
-- | -- | --
Win 10 (Chrome) | 102.0.5005.63 | http://somup.com/c3jbQuu9UZ 
Win 10 (Firefox) | 101.0 | http://somup.com/c3jbQuu9Ut
Win 10 (Edge) | 103.0.1264.37 | http://somup.com/c3jbQtu9U3
MAC (safari) | 15.3 | http://somup.com/c3jbQwu9Ug
Ipad (safari) | v15.1 | http://somup.com/c3jbQvu9Uw

</body>
</html>

**Comment by silvalaura** [comment]
No plans to fix.
