### ISSUE TITLE
Appbar>tabs>Search field is overlapping with Favorites button .

### ISSUE THREAD

**Issue by Uditsingh67** [cengage/react-magma#881]
**Describe the bug**
tabs>Search field is overlapping with Favorites button .

**To Reproduce**
**Steps to reproduce the behavior:**

1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/appbar--tabs
2. And Verify

**Expected behavior**
Search field should not overlapped with Favorites button.

**Screenshots**
http://somup.com/c3jFhBuRmC

**Desktop:**

- OS: [Win 10]
- Browser [chrome]
- Version [Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by silvalaura** [comment]
This is also occurring in the docs site: https://react-magma.cengage.com/version/3.1.1/api/appbar/

**Comment by silvalaura** [comment]
**Testing notes:**
- Check https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/appbar--tabs
- Check https://next--upbeat-sinoussi-f675aa.netlify.app/api/appbar/#nav_tabs

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : http://somup.com/c3611lvVjt
Thanks!
