### ISSUE TITLE
Button>all> Controls are not working for All component.

### ISSUE THREAD

**Issue by Uditsingh67** [cengage/react-magma#882]
**Describe the bug**
All>Controls are not working for All component. 

**To Reproduce**
**Steps to reproduce the behavior:**

1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/button--all
2. And Verify

**Expected behavior**
Controls should work for All component

**Screenshots**
http://somup.com/c3jF1PuRs1

**Desktop:**

- OS: [Win 10]
- Browser [chrome]
- Version [Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by silvalaura** [comment]
This is by design. No plans to fix.
