### ISSUE TITLE
PasswordInput>Default/Inverse/Error> 1 incomplete is appearing

### ISSUE THREAD

**Issue by Uditsingh67** [cengage/react-magma#888]
**Describe the bug**
Default/Inverse/Error> 1 incomplete is appearing.
**To Reproduce**
**Steps to reproduce the behavior:**

1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/passwordinput--default
2. Click on the Accessibility tab
3. And Verify

**Expected behavior**
0 incomplete should appear.

**Screenshots**
http://somup.com/c3jqhsuWr6

Desktop:

OS: [Win 10]
Browser [chrome]
Version [Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by silvalaura** [comment]
No plans to fix. The background image is coming from LastPass, and we have no control over it.

**Comment by Uditsingh67** [comment]
The issue is still reproducible:
**Storybook Link :** https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/passwordinput--inverse
**See Screen-cast :** http://somup.com/c3jvhUUlkn
