### ISSUE TITLE
Search>Default>The focus is appearing on both the search bar and cross button.

### ISSUE THREAD

**Issue by Uditsingh67** [cengage/react-magma#889]
**Describe the bug**
Default>The focus is appearing on both the search bar and cross button.

**QA Note: This issue impacts Select component.**

**To Reproduce**
1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/search--default&args=isClearable:true;inputSize:medium'
2. Click on 'Control' tab
3. Scroll down to 'isClearable'
4. Change to true 
5. Type 'Test' in search bar
6. Press tab
7. See error

**Expected behavior**
The focus shouldn't appear two things at the same time.

**Screenshots**
http://somup.com/c3jq1fuWrJ

**Desktop:**

- OS: [Win 10]
- Browser [chrome]
- Version [Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by silvalaura** [comment]
Testing Notes: 

Check the following stories:
[Input without Icon](https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/input--default&args=isClearable:true)
-- check with isClearable flag on and off
[Input with Icon](https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/input--icon-top):
-- check with isClearable flag on and off (ensure that if text fills the input, the text doesn't get covered by the icons)
-- change the iconPosition
-- change the inputSize
[Input with clickable Icon](https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/input--clickable-icon):
-- check with isClearable flag on and off (ensure that if text fills the input, the text doesn't get covered by the icons)
-- change the iconPosition
-- change the inputSize
[Search](https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/search--default&args=isClearable:true)
-- check with isClearable flag on and off
-- change the inputSize
[DatePicker](https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datepicker--default&args=isClearable:true)
-- check with isClearable flag on and off

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : 
<html>
<body>


OS | Version | Result
-- | -- | --
Win 10 (Chrome) | 102.0.5005.63 | (http://somup.com/c3jZjrUhqn)
Win 10 (Firefox) | 101.0 | (http://somup.com/c3jZjtUhqz)
Win 10 (Edge) | 103.0.1264.37 | (http://somup.com/c3jZjZUhqX)
MAC (safari) | 15.3 | (http://somup.com/c3jZjvUhqH)


</body>
</html>

**Comment by Uditsingh67** [comment]
Issue does not exist.
See Screen-cast : http://somup.com/c3jwitU2Tm
