### ISSUE TITLE
Inputs enhancement: Character counter

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#891]
**Purpose:** Define and add character counter functionality to text-based inputs.  This will provide valuable feedback to users when there are limits put on how many characters are allowed for submission.

**Figma:** https://www.figma.com/file/VoWYiiOKKppcYm5QLgPyDC/Form-Inputs?node-id=1%3A12778

**Inspiration:** https://designsystem.digital.gov/components/character-count/

Note: I have a feeling this will not simply use the maxlength attribute for inputs.  If that was the case, then it would stop you from entering more than the allowed characters and that's not exactly what we're going for here.

### AC

1.0 Verify when Character Counter is enabled, it appears below the input with the same styling as standard Helper Text, and that it gets the character limit from the [maxlength] attribute.
![image](https://user-images.githubusercontent.com/24397282/185651126-8683073d-b56e-44ef-b4b4-c63ace5bf520.png)
-- 1.1 Verify you can also still enable Helper Text and it appears below the Character Counter.
     ![image](https://user-images.githubusercontent.com/24397282/185651170-b6386240-7a19-4d18-901e-28ea1e226cf7.png)

2.0 Verify as you type characters into the input, the Character Counter updates and reflects how many allowed characters are left.
![image](https://user-images.githubusercontent.com/24397282/185651235-72178176-e3db-4ed6-adaa-3a5681227834.png)

3.0 Verify once you start typing characters over the limit, the input reacts by showing its error state, and the character counter's message reflects this as well.
     ![image](https://user-images.githubusercontent.com/24397282/185969744-b88a987b-f82b-4376-9d92-0afa91c102d6.png)
     ![image](https://user-images.githubusercontent.com/24397282/185969821-d2517f07-adf5-4240-871f-9833eafd7b2c.png)

-- 3.1 Verify the input can support multiple error messages in addition to the character counter.
     ![image](https://user-images.githubusercontent.com/24397282/185969929-c7cbc737-9cd6-4476-84ab-9d274f7d02bc.png)

4.0 Verify the character counter can be enabled on the following components:

- Input
- Text area

5.0 Correct grammar - Depending on the number of characters referenced in the message, we need to make sure the message is grammatically correct.
-- 5.1
--- 1 character allowed
--- 20 characters allowed
--- 0 characters left
--- 1 character left
--- 5 characters left
--- 1 character over limit
--- 40 characters over limit 

6.0 Accessibility
-- 6.1 Associate the character count message to the input. Use [aria-describedby] on the input to allow the message to be announced to those using screen readers.
-- 6.2 Use the "aria-live" attribute on character count message. Use [aria-live="polite"] so that updates to character count message are also announced when using a screen reader.

7.0 Validation vs Required
I think we need to consider that if the field itself is not required within a form, then the form can be submitted if the field is blank.  But once you start entering data into it, then you have to meet its requirements, even if the field itself is not required.  The actual validation logic for the form is still on the consumer, but it's just something we need to be aware of and possibly test for.

**Comment by orion-cengage** [comment]
Feedback from Perkins:

Hi Orion. I reviewed the prototype with NVDA/Chrome and VO/Safari and have some feedback for you to consider. The thing that concerns me is that even when using aria-live="polite" the remaining characters announcement might be disruptive to screen reader users when utilized in this way, especially if it were to be a long message that the user is entering into a textarea. What I would suggest is that the live region is implemented in a way that only announces the character limit at a specific interval. For example, you can use Javascript to update the aria-live value from "off" to "polite" when 80% of the characters have been typed. You could also have the value update to "polite" only when a certain number of characters are typed (for example, every 5 characters after the 80% is reached). Finally, you can update aria-live to "assertive" when the user goes over the character limit. I know this might require some scripting but I do believe it would be the best user experience for someone who is blind.

I would also recommend using aria-describedby to associate the <input> with the <div> that has aria-live so that the initial helper text ("4 characters allowed") is announced by screen readers when the field gains focus. The initial helper text is not announced when the page loads because aria-live will only announce a live region when the content inside it changes. I added aria-describedby to the <div> and it works well. It announces "Character Counter Edit Text 4 characters allowed" when the field gains focus, then it only announces the live region updates after that.

**Comment by Uditsingh67** [comment]
We have verified this ticket and found that this ticket is working as expected.
See Screen-cast : http://somup.com/c36qhXvFS3
Thanks!
