### ISSUE TITLE
Bug / Button docs / Content spilling outside of page on small screens

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#894]
Pages: 

- https://react-magma.cengage.com/version/3.1.0/api/button/
- https://react-magma.cengage.com/version/3.1.0/api/dropdown/
- https://react-magma.cengage.com/version/3.1.0/api/button-group/
- https://react-magma.cengage.com/version/3.1.0/api/combobox/
- https://react-magma.cengage.com/version/3.1.0/api/flex/
- https://react-magma.cengage.com/version/3.1.0/api/grid/
- https://react-magma.cengage.com/version/3.1.0/api/icon-button/
- https://react-magma.cengage.com/version/3.1.0/api/loading-indicator/
- https://react-magma.cengage.com/version/3.1.0/api/modal/
- https://react-magma.cengage.com/version/3.1.0/api/select/
- https://react-magma.cengage.com/version/3.1.0/api/toast/

Version found: 3.1.0

Bug: On small screens, some of the examples are spilling outside their container, causing the whole page to scroll horizontally.  These should be allowed to wrap within their containers or cut them off to prevent the whole page from scrolling horizontally.

![image](https://user-images.githubusercontent.com/24397282/186431169-9f0e1fe4-9ba0-4c82-a848-86cebe96abf9.png)

![image](https://user-images.githubusercontent.com/24397282/186431226-784bc4ac-a457-4cad-9750-0aee5d1c5b13.png)

![image](https://user-images.githubusercontent.com/24397282/186431718-ee5f4144-d4ec-490a-a724-d83e48706773.png)

**Comment by silvalaura** [comment]
Ah, good catch! I think this is because of ButtonGroup

**Comment by Uditsingh67** [comment]
The issue is **fixed**.
**See Screen-cast :**  http://somup.com/c3QrhIUCfi
Thanks!
