### ISSUE TITLE
Update Design Resources & Tools

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#898]
We should update our [Resources & Tools](https://react-magma.cengage.com/version/3.1.1/design-intro/get-started/#resources_&_tools) section of the docs to no longer have Sketch / Abstract / inVision.

**Comment by Uditsingh67** [comment]
Sketch / Abstract / inVision are no longer visible.
See Screen-cast : http://somup.com/c3XZhCwi3d
Thanks!
