### ISSUE TITLE
New Component: Toggle Button

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#904]
**Purpose:** Create a new Toggle Button component one or more buttons that can be toggled on and off.

**Figma:** https://www.figma.com/file/VoWYiiOKKppcYm5QLgPyDC/Components---Inputs?node-id=75%3A10654

![image](https://user-images.githubusercontent.com/24397282/197209974-a765e374-ecaa-497c-8bff-3d61192d6093.png)

### AC

1.0 The component uses the "Subtle" button styles, which **_can't_** be changed.

2.0 The component can consist of a single button on its own, or as a group of buttons.  Styling of the buttons (space between, border-radius) needs to update automatically.
![image](https://user-images.githubusercontent.com/24397282/197210185-98a498c2-8771-41e6-9766-bb34f7d50d17.png)

![image](https://user-images.githubusercontent.com/24397282/197211076-c7ce8715-3c87-4910-9556-060d769b4409.png)

![image](https://user-images.githubusercontent.com/24397282/197210216-4a5c70fa-097d-4aff-bd2a-86083473bb98.png)

![image](https://user-images.githubusercontent.com/24397282/197211153-28542815-331f-4c3d-9912-9714f166f79e.png)

3.0 Buttons may contain text only, icon only, or text + icon

4.0 Each button within the component needs to turn on and off via click/tap

5.0 Button states

-- 5.1 When the button is "on", it uses the styling of the "pressed/active" Secondary button.
![image](https://user-images.githubusercontent.com/24397282/197210398-f4da8d58-b130-4cda-872c-55f43d5ddc8e.png)

-- 5.2 Regardless of whether the button is currently on or off, it gets the hover and pressed styling when triggered

-- 5.3 A button can be disabled, but when it is in this component, the border styling needs to be consistent with the rest of the buttons.
![image](https://user-images.githubusercontent.com/24397282/197210538-c0004d1e-21f2-411c-8351-918d8e34ef14.png)

6.0 With exclusive selection set, selecting one option deselects any other.

7.0 With multiple selection set, multiple buttons can be on at the same time.

8.0 You can set any button to be turned on by default.

9.0 You can enforce that **_at least one button_** in the group must be on.

10.0 You can set the size small, medium (default), and large.
![image](https://user-images.githubusercontent.com/24397282/197210654-aeef01a3-f500-4a54-90ae-70bae3e8b59a.png)

![image](https://user-images.githubusercontent.com/24397282/197210904-a78b4097-1a72-42b7-bfa5-8162bfe1faac.png)

11.0 Accessibility

-- 11.1 Some good accessibility rules can be found here: https://mui.com/material-ui/react-toggle-button/#accessibility

-- 11.2 Keyboard - Toggle buttons are in DOM order. Navigate between them with the tab key. The button behavior follows standard keyboard semantics.

**Comment by hkrishna29** [comment]
1.0 The component uses the "Subtle" button styles, which can't be changed. - **Pass**
2.0 The component can consist of a single button on its own, or as a group of buttons. Styling of the buttons (space between, border-radius) needs to update automatically. - **Pass**
3.0 Buttons may contain text only, icon only, or text + icon  **Pass**
4.0 Each button within the component needs to turn on and off via click/tap **Pass**
5.0 Button states
-- 5.1 When the button is "on", it uses the styling of the "pressed/active" Secondary button.  **Pass**
-- 5.2 Regardless of whether the button is currently on or off, it gets the hover and pressed styling when triggered
-- 5.3 A button can be disabled, but when it is in this component, the border styling needs to be consistent with the rest of the buttons.
6.0 With exclusive selection set, selecting one option deselects any other. **Pass**
7.0 With multiple selection set, multiple buttons can be on at the same time. **Pass**
8.0 You can set any button to be turned on by default. **Pass**
9.0 You can enforce that at least one button in the group must be on. **Pass**
10.0 You can set the size small, medium (default), and large. **Pass**
11.0 Accessibility  **Pass**
-- 11.1 Some good accessibility rules can be found here: https://mui.com/material-ui/react-toggle-button/#accessibility
-- 11.2 Keyboard - Toggle buttons are in DOM order. Navigate between them with the tab key. The button behavior follows standard keyboard semantics.
