### ISSUE TITLE
Multi Combobox does not show the `isClearable` X

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#907]
**Describe the bug**
When using a Combobox with the `isMulti` prop + `isClearable`, the clearable X is not visible.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-magma-example-forked-mojyen
2. Notice the X is not visible for the multi combobox, but does work for the single one

**Expected behavior**
`isClearable` prop should function for both kinds of Comboboxes

**Screenshots**
![image](https://user-images.githubusercontent.com/91160746/187969735-2653091d-f869-4444-bf9a-fa9970099840.png)

**Comment by silvalaura** [comment]
Fix this in v3

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : http://somup.com/c36uhkvxim
Thanks!
