### ISSUE TITLE
Bug: Help icon on inputs not in the correct place

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#909]
Version found: 3.x

https://react-magma.cengage.com/version/3.1.1/api/input/#additional_children_(e.g._help_link)

The help icon on inputs is displaying inside the input, but it is supposed to be above the input. 
![image](https://user-images.githubusercontent.com/24397282/188652892-f9efc33a-c8bd-4809-b916-783c9d8c0d23.png)
 
This is currently displaying correctly in 2.x
![image](https://user-images.githubusercontent.com/24397282/188652766-6fd8b155-7bbe-4f18-9c14-6f772f4f8848.png)

Possible solution: Instead of forcing it to appear above the input using CSS positioning, should the element itself render outside of the container?

**Comment by silvalaura** [comment]
Good find. I think I missed this because this example of additional children is not in storybook. We should make sure we have this example there too.

**Comment by silvalaura** [comment]
**How to test**
- Test all Inputs (Input, PasswordInput, DatePicker, Search, etc) and ensure they are behaving as expected
- Specifically, test Input > With Children and confirm that the component visually looks how we expect. Test medium, large, isClearable.

**Comment by Uditsingh67** [comment]
The issue is fixed.
See Screen-cast : http://somup.com/c3611QvVjn
Thanks!
