### ISSUE TITLE
Enhancement: Allow label on inputs to display on the left

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#910]
**Purpose:** Add the ability to display the corresponding input label to the left of the input.  This includes the following components:

- Text input
- Text area
- Date
- Time
- Combobox
- Native select
- Password

### AC
1.0 The label should be right-aligned within its container so everything aligns properly when you stack multiple inputs.  See illustration below.

![image](https://user-images.githubusercontent.com/24397282/188665000-13630c85-94ca-403b-9001-7224449fac23.png)

**Comment by Uditsingh67** [comment]
Alignment is not displayed properly for **Error** , **Large** & **File** under input component.
See Screen-cast : http://somup.com/c3XnfPvBbz
Hence, Reopening the ticket.
Thanks!

**Comment by ccedrone** [comment]
These are actually displaying properly on the left in all examples. The labelWidth isn't showing, but is fully working, do we care to add it to the examples here in addition?
