### ISSUE TITLE
Verify gridArea behaves correctly on GridItem

### ISSUE THREAD

**Issue by greenervigil** [cengage/react-magma#916]
**Describe the bug**
The documentation examples of Grid use ```as``` instead of ```gridArea```.  When updating the examples to use ```gridArea``` they did not behave as they should have.  Investigate and update documentation accordingly. 

**To Reproduce**
1. Go to 'https://react-magma.cengage.com/version/3.1.1/api-intro/page-templates/'
2. Click on 'Edit in Codesandbox' for Global Header with Sidebar
3. Change the as props to gridArea
4. See behavior.

**Comment by silvalaura** [comment]
Fixed in https://github.com/cengage/react-magma/pull/1043
