### ISSUE TITLE
React Magma Versions> Version tag is not displayed in the header. 

### ISSUE THREAD

**Issue by Uditsingh67** [cengage/react-magma#936]
**Describe the bug**
React Magma Versions> Version tag is not displayed in the header.

**To Reproduce
Steps to reproduce the behavior:**

Go to https://docs-preview-646--upbeat-sinoussi-f675aa.netlify.app/api-intro/versions/#released_versions
Verify the Version tag is not displayed 

**Expected behavior**
 Version tag should display in the header.

**Comment by silvalaura** [comment]
This is not a bug.

@orion-cengage Do we want to keep this open, or close it because we don't have intentions to do this right now?
