### ISSUE TITLE
Multi Combobox: Support persistent menu

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#947]
We need the ability to allow users to maintain the combobox list of items open, so that users don't have to reopen the menu after each selection

## How to test

- Confirm that the hasPersistentMenu prop behaves as expected for Multi Comboboxes
- Confirm that keyboard navigation behaves as expected (escape, tab, up/down, left/right arrow keys)
- Confirm that the placeholder text disappears for Multi Comboboxes once at least one item has been selected

**Comment by Uditsingh67** [comment]
Verified the ticket  and found this to be working as desired.
See Screen-cast : http://somup.com/c3XnhTvBFm
Thanks!
