### ISSUE TITLE
Multi Combobox: when used inside a form, deleting an item submits the form

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#953]
**Describe the bug**
After a user selects an item, if they were to delete it by clicking on it, this action would cause the form that the multiCombobox is within to submit. I think the issue is that the button that gets rendered when a user selects an item doesn’t have its “type” set to  “button” and defaults to “submit.”

**To Reproduce**
1. Go to https://codesandbox.io/s/react-magma-multi-combobox-issue-when-changing-item-list-forked-u2iwzu?file=/example.tsx
2. If you select the red item, the form gets submitted. This only seems to happen when there is more than one item selected

**Expected behavior**
Deleting an item does not submit the form

**Comment by Uditsingh67** [comment]
@silvalaura 
Where should i test this ticket?

**Comment by silvalaura** [comment]
@Uditsingh67 This storybook example is wrapped in a form
https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/combobox--full-page-example

**Comment by Uditsingh67** [comment]
The issue is **fixed.**
**See Screen-cast :** http://somup.com/c3XffAvp7c
Thanks!
