### ISSUE TITLE
Replace custom icon - BooksWfIcon

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#969]
The provided icon for "BooksWFIcon" was incorrect. Once I get the new icon from Kevin, we need to place it and get it into the next release.

**Comment by silvalaura** [comment]
**Testing Notes:**

Two icons were updated:

**Before (https://react-magma.cengage.com/version/3.2.0/api/icon/)**
<img width="314" alt="image" src="https://user-images.githubusercontent.com/91160746/209154838-1bf8abc6-8860-491c-8010-352ea32aff58.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/91160746/209154894-6af4b6f7-11d5-4285-9173-88f78a447f52.png">

**After (https://next--upbeat-sinoussi-f675aa.netlify.app/api/icon/)**
<img width="303" alt="image" src="https://user-images.githubusercontent.com/91160746/209155076-61ea5290-cb12-444b-b574-d0aeae7482a5.png">
<img width="303" alt="image" src="https://user-images.githubusercontent.com/91160746/209155037-18252471-b255-4e21-ad32-fc320b6b21a7.png">

**Comment by hkrishna29** [comment]
The icons 
'BooksWficon' is updated as expected 
'DirectionsRailwayIcon' is available now 

**Testing proof**: http://somup.com/c3l3oDwHoY
