### ISSUE TITLE
cleanup component indexes to export instead of being the main component 

### ISSUE THREAD

**Issue by aaronmaturen** [cengage/react-magma#97]
Currently when using components inside react-magma-dom the sub components often have to be imported from multiple files

```
import { Card } from '../Card';
import { CardHeading } from '../Card/CardHeading';
import { CardBody } from '../Card/CardBody';
```

There should be a `Card/Card.tsx` a `Card/CardHeading.tsx` and a `Card/CardBody.tsx`
and then the `Card/index.ts` just does

```
export { Card, CardProps } from './Card';
export { CardBody, CardBodyProps } from './CardBody';
export { CardHeading, CardHeadingProps } from './CardHeading';
```

this would allow all the downstream components to just do 
```
import { Card, CardHeading, CardBody } from '../Card'
```

**Comment by joasmi723** [comment]
This applies to Card, Dropdown, Modal, NavTabs, Table, Tabs.
