### ISSUE TITLE
Update yellows in the color palette

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#975]
Due to cross-branding with NGL, we need to update the yellows in the color palette, which really only impacts the Marketing button. There is a color change on the text in that button as well.

Secondary color
- secondary-500 = #FFCC00
- secondary-600 = #E3B500
- secondary-700 = #C69F00

![image](https://user-images.githubusercontent.com/24397282/206294944-b4b81a1d-f9d8-4f52-83f6-c673becf398d.png)

Marketing button
- button text = neutral-700
- button hover text = neutral-700
- button pressed text = neutral-800

![image](https://user-images.githubusercontent.com/24397282/206294997-302a7a73-bba0-4b9b-80fc-920d379f385e.png)

**Comment by silvalaura** [comment]
@orion-cengage What about the marketing link? Will it still be color primary and on hover the changes above apply?

**Comment by hkrishna29** [comment]
The color palate for Marketing button is working as expected

**Testing Proof:**
http://somup.com/c3l3oawHDS
http://somup.com/c3l3opwHb3
					                             
**Normal**		
Background color = #FFCC00	|| 255, 204, 0 ||	Pass
Text color = #454545 (neutral-700) || 69, 69, 69) || Pass

**Hover**		
Background color = #F3C200) || 243, 194, 0) || Pass
Text color = #454545 (neutral-700)	69, 69, 69) || Pass

**Pressed**		
Background color = #E7B900) || 231, 185, 0) || Pass
Text color = #2D2D2D (neutral-800)) || 45, 45, 45) || Pass
