### ISSUE TITLE
Support adding children on the right side of Alerts

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#992]
We want to support the ability to add different components such as buttons or badges on the right side on an alert. It should replace the space that the dismissible buttons takes up when alerts are not dismissible, or be to the left of the X when the alert is dismissible.

![image](https://user-images.githubusercontent.com/91160746/212998185-c5fe4d8c-5009-4132-96c1-f71f1f533c69.png)

**Use cases:** 
- Ability to add a button/badge when an alert is dismissible
- Ability to add a button/badge when an alert is NOT dismissible
- When the alert text is long, it should wrap and should not interfere with the newly added space on the right

**Acceptance Criteria:**
- Documentation updates to Alert and Banner to illustrate example on how to do this using flexbox. This example should show with and without the close button.

**Comment by hkrishna29** [comment]
Badges and buttons are displayed right hand side of the alert , where the buttons are clickable and badges are not.  
http://somup.com/c0nrYoyhcx
