### ISSUE TITLE
Banner: Focus is getting truncated from the bottom side on 'X' icon

### ISSUE THREAD

**Issue by hkrishna29** [cengage/react-magma#994]
**To Reproduce**
1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/banner--default'
2. Click on 'Banner'
3. Tab through the preview.
4. Focus indicator is truncated at the bottom side of 'x' button

**Expected behavior**
Focus indicator should never be truncated 

**Screenshots**
https://screencast-o-matic.com/watch/c0VIQDVwydw

**OS / Br** 
All

**Notes**
We may want to consider adjusting the focus on banners so that it doesn't use the 1px offset.

**Comment by orion-cengage** [comment]
Maybe we'll polish this up at some point, but this is not what I would consider a bug.

**Comment by silvalaura** [comment]
Indirectly fixed with #1087

**Comment by orion-cengage** [comment]
Verified fix. Looks good.
