### ISSUE TITLE
Example drop down in preview is expanding with respect to the error message 

### ISSUE THREAD

**Issue by hkrishna29** [cengage/react-magma#996]
**Steps to reproduce the behavior:**

1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/combobox--left-aligned-label-with-container'
2. Enter data in 'Error Message' control
3. Note that the Example drop down in preview is expanding with respect to the error message 

**Expected behavior**
Example dropdown width should not be relevant to error message

**Screenshots**
https://somup.com/c0V0hsxYHn

**OS / Br**
All

** Note:**
This is also occurring in 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/select--left-aligned-label-with-container'

**Comment by orion-cengage** [comment]
In this example, there isn't anything controlling the width of the input, so it is naturally growing to accommodate the additional text. This is expected.

If you want the example to reflect the real world more accurately, then we need to restrict the width of its container, or the input itself, which will force the text to wrap.

**Comment by silvalaura** [comment]
Will be fixed as part of #993
