### ISSUE TITLE
Page number is not changing when enter the data into 'defaultPage' controls

### ISSUE THREAD

**Issue by hkrishna29** [cengage/react-magma#997]
**Steps to reproduce the behavior:**

1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/pagination--default'
2. UPdate default page number in control
3. Page number is not changing when enter the data into 'defaultPage' controls

**Expected behavior**
When page number is updated via control , in preview it should be updated

**Screenshots**
https://somup.com/c0VZhMx35q

**OS / Br**
All

**Comment by silvalaura** [comment]
This is not a bug. When the defaultPage is changed and the page is refreshed, the behavior looks as expected.

**Comment by hkrishna29** [comment]
closing the ticket w.r.t comments provided above
